// Diccionarios de la interfaz: castellano (el idioma en que está escrita la app), English, Català,
// Italiano, Français y Deutsch.
// - DOM: textos que salen tal cual en pantalla (o en atributos como placeholder y aria-label). La
//   clave es el texto en castellano con los espacios normalizados. Una clave que termina en ":"
//   también vale como prefijo (p. ej. "No se pudo compartir:" + el motivo).
// - CODIGO: frases que el código compone con datos (nombres, números, plurales) y que se piden con
//   trad('frase con {marcadores}', { marcador: valor }); y palabras sueltas que solo se usan así.
// Esto es SOLO la interfaz: los datos (nombres, categorías, copias, exportaciones) no se traducen.
// Cada entrada es [es, en, ca, it, fr, de].
(function () {
  const DOM = [
    // ---- atributos (aria-label, placeholder…)
    [`Volver`, `Back`, `Enrere`, `Indietro`, `Retour`, `Zurück`],
    [`Buscar documento`, `Search document`, `Cerca un document`, `Cerca documento`, `Rechercher un document`, `Dokument suchen`],
    [`Ver en lista (categorías)`, `View as list (categories)`, `Veure en llista (categories)`, `Vedi come elenco (categorie)`, `Voir en liste (catégories)`, `Als Liste anzeigen (Kategorien)`],
    [`Ajustes`, `Settings`, `Ajustos`, `Impostazioni`, `Paramètres`, `Einstellungen`],
    [`Subir documento`, `Upload document`, `Puja un document`, `Carica documento`, `Importer un document`, `Dokument hochladen`],
    [`Opciones de esta persona`, `Options for this person`, `Opcions d'aquesta persona`, `Opzioni per questa persona`, `Options pour cette personne`, `Optionen für diese Person`],
    [`Cerrar aviso`, `Close notice`, `Tanca l'avís`, `Chiudi l'avviso`, `Fermer l'avis`, `Hinweis schließen`],
    [`Cancelar selección`, `Cancel selection`, `Cancel·la la selecció`, `Annulla selezione`, `Annuler la sélection`, `Auswahl abbrechen`],
    [`Ver en cuadrícula (personas)`, `View as grid (people)`, `Veure en quadrícula (persones)`, `Vedi come griglia (persone)`, `Voir en grille (personnes)`, `Als Raster anzeigen (Personen)`],
    [`Buscar documento…`, `Search document…`, `Cerca un document…`, `Cerca documento…`, `Rechercher un document…`, `Dokument suchen…`],
    [`Cambiar imagen`, `Change image`, `Canvia la imatge`, `Cambia immagine`, `Changer l'image`, `Bild ändern`],
    [`Renombrar persona`, `Rename person`, `Canvia el nom de la persona`, `Rinomina persona`, `Renommer la personne`, `Person umbenennen`],
    [`Eliminar persona`, `Delete person`, `Elimina la persona`, `Elimina persona`, `Supprimer la personne`, `Person löschen`],
    [`Renombrar categoría`, `Rename category`, `Canvia el nom de la categoria`, `Rinomina categoria`, `Renommer la catégorie`, `Kategorie umbenennen`],
    [`Cambiar color`, `Change colour`, `Canvia el color`, `Cambia colore`, `Changer la couleur`, `Farbe ändern`],
    [`Eliminar categoría`, `Delete category`, `Elimina la categoria`, `Elimina categoria`, `Supprimer la catégorie`, `Kategorie löschen`],
    [`Añadir nombre`, `Add name`, `Afegeix el nom`, `Aggiungi nome`, `Ajouter un nom`, `Namen hinzufügen`],
    [`Girar 90 grados a la izquierda`, `Rotate 90 degrees left`, `Gira 90 graus cap a l'esquerra`, `Ruota di 90 gradi a sinistra`, `Pivoter de 90 degrés vers la gauche`, `90 Grad nach links drehen`],
    [`Girar la foto`, `Rotate the photo`, `Gira la foto`, `Ruota la foto`, `Faire pivoter la photo`, `Foto drehen`],
    [`Girar 90 grados a la derecha`, `Rotate 90 degrees right`, `Gira 90 graus cap a la dreta`, `Ruota di 90 gradi a destra`, `Pivoter de 90 degrés vers la droite`, `90 Grad nach rechts drehen`],
    [`Alejar`, `Zoom out`, `Allunya`, `Rimpicciolisci`, `Dézoomer`, `Verkleinern`],
    [`Zoom de la foto`, `Photo zoom`, `Zoom de la foto`, `Zoom della foto`, `Zoom de la photo`, `Foto-Zoom`],
    [`Acercar`, `Zoom in`, `Acosta`, `Ingrandisci`, `Zoomer`, `Vergrößern`],
    [`Tiene documentos caducados o a punto de caducar`, `Has expired documents or ones about to expire`, `Té documents caducats o a punt de caducar`, `Ha documenti scaduti o in scadenza`, `A des documents expirés ou bientôt expirés`, `Hat abgelaufene oder bald ablaufende Dokumente`],
    [`Descargar`, `Download`, `Descarrega`, `Scarica`, `Télécharger`, `Herunterladen`],
    [`Opciones del documento`, `Document options`, `Opcions del document`, `Opzioni del documento`, `Options du document`, `Dokumentoptionen`],
    [`Añadir página`, `Add page`, `Afegeix una pàgina`, `Aggiungi pagina`, `Ajouter une page`, `Seite hinzufügen`],
    [`Ej: DNI`, `E.g. ID card`, `Ex.: DNI`, `Es.: carta d'identità`, `Ex. : carte d'identité`, `Z. B. Personalausweis`],
    [`Nombre de esta página`, `Name of this page`, `Nom d'aquesta pàgina`, `Nome di questa pagina`, `Nom de cette page`, `Name dieser Seite`],
    [`Quitar página`, `Remove page`, `Treu la pàgina`, `Rimuovi pagina`, `Retirer la page`, `Seite entfernen`],
    [`Volver a Ajustes`, `Back to Settings`, `Torna a Ajustos`, `Torna a Impostazioni`, `Retour aux paramètres`, `Zurück zu Einstellungen`],
    [`Categoría`, `Category`, `Categoria`, `Categoria`, `Catégorie`, `Kategorie`],

    // ---- bienvenida y nubes
    [`Documentación`, `Documents`, `Documentació`, `Documenti`, `Documents`, `Dokumente`],
    [`DOCUMENTACIÓN`, `DOCUMENTS`, `DOCUMENTACIÓ`, `DOCUMENTI`, `DOCUMENTS`, `DOKUMENTE`],
    [`El DNI, carnet de conducir, tarjeta de discapacidad y demás papeles de tu gente, siempre a mano.`, `ID cards, driving licences, disability cards and all the other paperwork of your people, always at hand.`, `El DNI, el carnet de conduir, la targeta de discapacitat i la resta de papers de la teva gent, sempre a mà.`, `Carta d'identità, patente, tessera di invalidità e tutti gli altri documenti della tua famiglia, sempre a portata di mano.`, `La carte d'identité, le permis de conduire, la carte d'invalidité et tous les autres papiers de vos proches, toujours à portée de main.`, `Personalausweis, Führerschein, Schwerbehindertenausweis und all die anderen Papiere deiner Familie, immer griffbereit.`],
    [`Empezar de nuevo`, `Start fresh`, `Comença de nou`, `Inizia da zero`, `Recommencer`, `Neu anfangen`],
    [`Primera vez, sin nada guardado`, `First time, nothing saved yet`, `Primera vegada, sense res desat`, `Prima volta, nulla di salvato`, `Première fois, rien d'enregistré`, `Erstes Mal, noch nichts gespeichert`],
    [`Iniciar sesión en tus nubes`, `Sign in to your clouds`, `Inicia la sessió als teus núvols`, `Accedi ai tuoi cloud`, `Se connecter à vos clouds`, `Bei deinen Clouds anmelden`],
    [`Recuperar mi copia desde una nube`, `Restore my copy from a cloud`, `Recupera la meva còpia des d'un núvol`, `Recupera la mia copia da un cloud`, `Récupérer ma copie depuis un cloud`, `Meine Kopie aus einer Cloud wiederherstellen`],
    [`Importar archivo`, `Import file`, `Importa un fitxer`, `Importa file`, `Importer un fichier`, `Datei importieren`],
    [`Cargar una copia (.txt) que exporté antes`, `Load a copy (.txt) that I exported earlier`, `Carrega una còpia (.txt) que vaig exportar abans`, `Carica una copia (.txt) esportata in precedenza`, `Charger une copie (.txt) exportée auparavant`, `Eine zuvor exportierte Kopie (.txt) laden`],
    [`Sin conectar ninguna nube, tus documentos solo estarán en este móvil.`, `Without connecting a cloud, your documents will only be on this phone.`, `Sense connectar cap núvol, els teus documents només estaran en aquest mòbil.`, `Senza collegare un cloud, i tuoi documenti resteranno solo su questo telefono.`, `Sans connecter de cloud, vos documents ne seront que sur ce téléphone.`, `Ohne eine Cloud zu verbinden, sind deine Dokumente nur auf diesem Handy.`],
    [`Podrás conectar una cuando quieras en Ajustes → Copias de seguridad. Esta app no tiene servidor propio.`, `You can connect one whenever you like in Settings → Backups. This app has no server of its own.`, `Podràs connectar-ne un quan vulguis a Ajustos → Còpies de seguretat. Aquesta app no té servidor propi.`, `Potrai collegarne uno quando vuoi in Impostazioni → Backup. Questa app non ha un server proprio.`, `Vous pourrez en connecter un quand vous voulez dans Paramètres → Sauvegardes. Cette appli n'a pas de serveur propre.`, `Du kannst jederzeit eine unter Einstellungen → Sicherungen verbinden. Diese App hat keinen eigenen Server.`],
    [`¿Dónde está tu copia?`, `Where is your copy?`, `On és la teva còpia?`, `Dove si trova la tua copia?`, `Où se trouve votre copie ?`, `Wo ist deine Kopie?`],
    [`Conéctala y se recuperará todo en este móvil.`, `Connect it and everything will be restored on this phone.`, `Connecta-la i es recuperarà tot en aquest mòbil.`, `Collegala e tutto verrà ripristinato su questo telefono.`, `Connectez-le et tout sera restauré sur ce téléphone.`, `Verbinde sie, und alles wird auf diesem Handy wiederhergestellt.`],
    [`Conectar con Google Drive`, `Connect with Google Drive`, `Connecta amb Google Drive`, `Collega Google Drive`, `Connecter avec Google Drive`, `Mit Google Drive verbinden`],
    [`Conectar con Dropbox`, `Connect with Dropbox`, `Connecta amb Dropbox`, `Collega Dropbox`, `Connecter avec Dropbox`, `Mit Dropbox verbinden`],
    [`Instala la app en tu móvil para abrirla más rápido`, `Install the app on your phone to open it faster`, `Instal·la l'app al mòbil per obrir-la més ràpid`, `Installa l'app sul telefono per aprirla più velocemente`, `Installez l'appli sur votre téléphone pour l'ouvrir plus vite`, `Installiere die App auf deinem Handy, um sie schneller zu öffnen`],
    [`Instalar`, `Install`, `Instal·la`, `Installa`, `Installer`, `Installieren`],
    [`0 seleccionados`, `0 selected`, `0 seleccionats`, `0 selezionati`, `0 sélectionnés`, `0 ausgewählt`],
    [`Compartir`, `Share`, `Comparteix`, `Condividi`, `Partager`, `Teilen`],
    [`No se pudo conectar con Google.`, `Could not connect to Google.`, `No s'ha pogut connectar amb Google.`, `Impossibile connettersi a Google.`, `Impossible de se connecter à Google.`, `Verbindung zu Google fehlgeschlagen.`],
    [`No se pudo completar la conexión.`, `The connection could not be completed.`, `No s'ha pogut completar la connexió.`, `Impossibile completare la connessione.`, `La connexion n'a pas pu être terminée.`, `Die Verbindung konnte nicht hergestellt werden.`],
    [`Google no está disponible ahora mismo.`, `Google is not available right now.`, `Google no està disponible ara mateix.`, `Google non è disponibile in questo momento.`, `Google n'est pas disponible pour le moment.`, `Google ist gerade nicht verfügbar.`],
    [`Importando…`, `Importing…`, `Important…`, `Importazione…`, `Importation…`, `Importiere…`],
    [`Preparando tus documentos…`, `Preparing your documents…`, `Preparant els teus documents…`, `Preparazione dei tuoi documenti…`, `Préparation de vos documents…`, `Deine Dokumente werden vorbereitet…`],
    [`No se pudieron guardar los datos en este móvil (sin espacio).`, `Could not save the data on this phone (out of space).`, `No s'han pogut desar les dades en aquest mòbil (sense espai).`, `Impossibile salvare i dati su questo telefono (spazio esaurito).`, `Impossible d'enregistrer les données sur ce téléphone (espace insuffisant).`, `Die Daten konnten nicht auf diesem Handy gespeichert werden (kein Speicherplatz).`],
    [`Sin categoría`, `Uncategorised`, `Sense categoria`, `Senza categoria`, `Sans catégorie`, `Ohne Kategorie`],
    [`Sin persona`, `No person`, `Sense persona`, `Nessuna persona`, `Aucune personne`, `Keine Person`],

    // ---- aviso de "solo en este móvil"
    [`Solo en este móvil`, `Only on this phone`, `Només en aquest mòbil`, `Solo su questo telefono`, `Uniquement sur ce téléphone`, `Nur auf diesem Handy`],
    [`Tus documentos están guardados solo en este móvil. Si borras los datos de la app o cambias de móvil, se perderían. Conecta una nube (Google Drive o Dropbox) para tener copia de seguridad.`, `Your documents are stored only on this phone. If you clear the app data or change phone, they would be lost. Connect a cloud (Google Drive or Dropbox) to have a backup.`, `Els teus documents es guarden només en aquest mòbil. Si esborres les dades de l'app o canvies de mòbil, es perdrien. Connecta un núvol (Google Drive o Dropbox) per tenir còpia de seguretat.`, `I tuoi documenti sono salvati solo su questo telefono. Se cancelli i dati dell'app o cambi telefono, andrebbero persi. Collega un cloud (Google Drive o Dropbox) per avere un backup.`, `Vos documents ne sont enregistrés que sur ce téléphone. Si vous effacez les données de l'appli ou changez de téléphone, ils seraient perdus. Connectez un cloud (Google Drive ou Dropbox) pour avoir une sauvegarde.`, `Deine Dokumente sind nur auf diesem Handy gespeichert. Wenn du die App-Daten löschst oder das Handy wechselst, gehen sie verloren. Verbinde eine Cloud (Google Drive oder Dropbox), um eine Sicherung zu haben.`],
    [`También puedes guardar una copia en un archivo desde`, `You can also save a copy to a file from`, `També pots desar una còpia en un fitxer des de`, `Puoi anche salvare una copia in un file da`, `Vous pouvez aussi enregistrer une copie dans un fichier depuis`, `Du kannst auch eine Kopie in einer Datei speichern unter`],
    [`Ajustes → Exportar copia`, `Settings → Export copy`, `Ajustos → Exporta una còpia`, `Impostazioni → Esporta copia`, `Paramètres → Exporter une copie`, `Einstellungen → Kopie exportieren`],
    [`, y recuperarla después con`, `, and restore it later with`, `, i recuperar-la després amb`, `, e recuperarla in seguito con`, `, et la récupérer ensuite avec`, `, und sie später wiederherstellen mit`],
    [`Importar copia`, `Import copy`, `Importa una còpia`, `Importa copia`, `Importer une copie`, `Kopie importieren`],
    [`No volver a mostrar este aviso`, `Don't show this notice again`, `No tornis a mostrar aquest avís`, `Non mostrare più questo avviso`, `Ne plus afficher cet avis`, `Diesen Hinweis nicht mehr anzeigen`],
    [`Conectar una nube`, `Connect a cloud`, `Connecta un núvol`, `Collega un cloud`, `Connecter un cloud`, `Cloud verbinden`],
    [`Cerrar`, `Close`, `Tanca`, `Chiudi`, `Fermer`, `Schließen`],

    // ---- estado de las nubes (Ajustes)
    [`Copiando…`, `Copying…`, `Copiant…`, `Copia in corso…`, `Copie en cours…`, `Kopiere…`],
    [`Hay que volver a conectar`, `You need to reconnect`, `Cal tornar a connectar`, `Devi ricollegare`, `Il faut reconnecter`, `Muss neu verbunden werden`],
    [`Sincronizado`, `Synced`, `Sincronitzat`, `Sincronizzato`, `Synchronisé`, `Synchronisiert`],
    [`Conectar`, `Connect`, `Connecta`, `Collega`, `Connecter`, `Verbinden`],
    [`Reconectar`, `Reconnect`, `Torna a connectar`, `Ricollega`, `Reconnecter`, `Erneut verbinden`],
    [`Desconectar`, `Disconnect`, `Desconnecta`, `Scollega`, `Déconnecter`, `Trennen`],
    [`Sin conectar`, `Not connected`, `Sense connectar`, `Non collegato`, `Non connecté`, `Nicht verbunden`],
    [`Ver carpeta`, `View folder`, `Veure la carpeta`, `Vedi cartella`, `Voir le dossier`, `Ordner ansehen`],
    [`Conecta una nube para tener copia de seguridad.`, `Connect a cloud to have a backup.`, `Connecta un núvol per tenir còpia de seguretat.`, `Collega un cloud per avere un backup.`, `Connectez un cloud pour avoir une sauvegarde.`, `Verbinde eine Cloud, um eine Sicherung zu haben.`],
    [`Revisa tus copias`, `Check your backups`, `Revisa les teves còpies`, `Controlla i tuoi backup`, `Vérifiez vos sauvegardes`, `Überprüfe deine Sicherungen`],
    [`Enviando los cambios a tus nubes.`, `Sending the changes to your clouds.`, `Enviant els canvis als teus núvols.`, `Invio delle modifiche ai tuoi cloud in corso.`, `Envoi des modifications vers vos clouds.`, `Änderungen werden an deine Clouds gesendet.`],
    [`Copia pendiente`, `Backup pending`, `Còpia pendent`, `Backup in sospeso`, `Sauvegarde en attente`, `Sicherung ausstehend`],
    [`Todo a salvo`, `All safe`, `Tot segur`, `Tutto al sicuro`, `Tout est en sécurité`, `Alles gesichert`],
    [`No hay ninguna nube conectada: no existe ninguna copia de seguridad.`, `No cloud is connected: there is no backup at all.`, `No hi ha cap núvol connectat: no existeix cap còpia de seguretat.`, `Nessun cloud collegato: non esiste alcun backup.`, `Aucun cloud n'est connecté : il n'existe aucune sauvegarde.`, `Keine Cloud verbunden: Es gibt überhaupt keine Sicherung.`],

    // ---- cerrar sesión (tres avisos)
    [`Aviso 1 de 3`, `Warning 1 of 3`, `Avís 1 de 3`, `Avviso 1 di 3`, `Avertissement 1 sur 3`, `Warnung 1 von 3`],
    [`Si cierras la sesión se borrarán de este móvil todos los documentos y sus archivos. No se podrán recuperar.`, `If you sign out, all documents and their files will be deleted from this phone. They cannot be recovered.`, `Si tanques la sessió s'esborraran d'aquest mòbil tots els documents i els seus fitxers. No es podran recuperar.`, `Se esci, tutti i documenti e i loro file verranno cancellati da questo telefono. Non potranno essere recuperati.`, `Si vous vous déconnectez, tous les documents et leurs fichiers seront supprimés de ce téléphone. Ils ne pourront pas être récupérés.`, `Wenn du dich abmeldest, werden alle Dokumente und ihre Dateien von diesem Handy gelöscht. Sie können nicht wiederhergestellt werden.`],
    [`Cancelar`, `Cancel`, `Cancel·la`, `Annulla`, `Annuler`, `Abbrechen`],
    [`Guardar antes una copia en un archivo`, `First save a copy to a file`, `Desa abans una còpia en un fitxer`, `Salva prima una copia in un file`, `Enregistrer d'abord une copie dans un fichier`, `Zuerst eine Kopie in einer Datei speichern`],
    [`Entiendo el riesgo, continuar`, `I understand the risk, continue`, `Entenc el risc, continua`, `Capisco il rischio, continua`, `Je comprends le risque, continuer`, `Ich verstehe das Risiko, weiter`],
    [`Aviso 2 de 3`, `Warning 2 of 3`, `Avís 2 de 3`, `Avviso 2 di 3`, `Avertissement 2 sur 3`, `Warnung 2 von 3`],
    [`Esta es la única copia que existe. Si tienes un solo momento de duda, cancela y conecta una nube en Ajustes → Copias de seguridad.`, `This is the only copy that exists. If you have even a moment of doubt, cancel and connect a cloud in Settings → Backups.`, `Aquesta és l'única còpia que existeix. Si tens un sol moment de dubte, cancel·la i connecta un núvol a Ajustos → Còpies de seguretat.`, `Questa è l'unica copia esistente. Se hai anche solo un momento di dubbio, annulla e collega un cloud in Impostazioni → Backup.`, `C'est la seule copie qui existe. Si vous avez le moindre doute, annulez et connectez un cloud dans Paramètres → Sauvegardes.`, `Dies ist die einzige vorhandene Kopie. Wenn du auch nur einen Moment zweifelst, brich ab und verbinde eine Cloud unter Einstellungen → Sicherungen.`],
    [`No, cancelar`, `No, cancel`, `No, cancel·la`, `No, annulla`, `Non, annuler`, `Nein, abbrechen`],
    [`Sí, quiero continuar`, `Yes, I want to continue`, `Sí, vull continuar`, `Sì, voglio continuare`, `Oui, je veux continuer`, `Ja, ich möchte fortfahren`],
    [`Aviso 3 de 3: último`, `Warning 3 of 3: last`, `Avís 3 de 3: l'últim`, `Avviso 3 di 3: ultimo`, `Avertissement 3 sur 3 : dernier`, `Warnung 3 von 3: letzte`],
    [`Esto no se puede deshacer.`, `This cannot be undone.`, `Això no es pot desfer.`, `Questa azione non può essere annullata.`, `Cette action est irréversible.`, `Dies kann nicht rückgängig gemacht werden.`],
    [`Para confirmar, escribe`, `To confirm, type`, `Per confirmar, escriu`, `Per confermare, scrivi`, `Pour confirmer, tapez`, `Zum Bestätigen tippe`],
    [`en el recuadro.`, `in the box.`, `al quadre.`, `nel campo.`, `dans le champ.`, `in das Feld ein.`],
    [`Borrar todo y cerrar sesión`, `Delete everything and sign out`, `Esborra-ho tot i tanca la sessió`, `Cancella tutto ed esci`, `Tout supprimer et se déconnecter`, `Alles löschen und abmelden`],

    // ---- búsqueda, personas y categorías
    [`Escribe el nombre de un documento para buscarlo entre todas las personas.`, `Type a document name to find it among all people.`, `Escriu el nom d'un document per trobar-lo entre totes les persones.`, `Scrivi il nome di un documento per trovarlo tra tutte le persone.`, `Tapez le nom d'un document pour le retrouver parmi toutes les personnes.`, `Gib den Namen eines Dokuments ein, um es bei allen Personen zu finden.`],
    [`No se ha encontrado ningún documento con ese nombre.`, `No document with that name was found.`, `No s'ha trobat cap document amb aquest nom.`, `Non è stato trovato nessun documento con questo nome.`, `Aucun document avec ce nom n'a été trouvé.`, `Es wurde kein Dokument mit diesem Namen gefunden.`],
    [`Todavía no tienes a nadie aquí.`, `You don't have anyone here yet.`, `Encara no tens ningú aquí.`, `Non hai ancora nessuno qui.`, `Vous n'avez encore personne ici.`, `Du hast hier noch niemanden.`],
    [`Añade a la primera con el botón de abajo. Para añadir más adelante, ve a Ajustes → "Personas". Si ya tenías una copia, conéctala en Ajustes → "Copias de seguridad" (o usa "Importar copia" si te la pasaron en un archivo).`, `Add the first one with the button below. To add more later, go to Settings → "People". If you already had a copy, connect it in Settings → "Backups" (or use "Import copy" if it was given to you as a file).`, `Afegeix la primera amb el botó de sota. Per afegir-ne més endavant, ves a Ajustos → "Persones". Si ja tenies una còpia, connecta-la a Ajustos → "Còpies de seguretat" (o fes servir "Importa una còpia" si te la van passar en un fitxer).`, `Aggiungi la prima con il pulsante qui sotto. Per aggiungerne altre in seguito, vai in Impostazioni → "Persone". Se avevi già una copia, collegala in Impostazioni → "Backup" (o usa "Importa copia" se te l'hanno passata in un file).`, `Ajoutez la première avec le bouton ci-dessous. Pour en ajouter d'autres plus tard, allez dans Paramètres → « Personnes ». Si vous aviez déjà une copie, connectez-la dans Paramètres → « Sauvegardes » (ou utilisez « Importer une copie » si on vous l'a transmise dans un fichier).`, `Füge die erste mit der Schaltfläche unten hinzu. Um später weitere hinzuzufügen, gehe zu Einstellungen → „Personen". Wenn du schon eine Kopie hattest, verbinde sie unter Einstellungen → „Sicherungen" (oder nutze „Kopie importieren", wenn sie dir als Datei gegeben wurde).`],
    [`Añadir`, `Add`, `Afegeix`, `Aggiungi`, `Ajouter`, `Hinzufügen`],
    [`Hacer foto`, `Take photo`, `Fes una foto`, `Scatta foto`, `Prendre une photo`, `Foto aufnehmen`],
    [`Galería`, `Gallery`, `Galeria`, `Galleria`, `Galerie`, `Galerie`],
    [`Icono`, `Icon`, `Icona`, `Icona`, `Icône`, `Symbol`],
    [`Ajustar foto`, `Adjust photo`, `Ajusta la foto`, `Regola foto`, `Ajuster la photo`, `Foto anpassen`],
    [`Foto actualizada`, `Photo updated`, `Foto actualitzada`, `Foto aggiornata`, `Photo mise à jour`, `Foto aktualisiert`],
    [`Icono actualizado`, `Icon updated`, `Icona actualitzada`, `Icona aggiornata`, `Icône mise à jour`, `Symbol aktualisiert`],
    [`Nombre actualizado`, `Name updated`, `Nom actualitzat`, `Nome aggiornato`, `Nom mis à jour`, `Name aktualisiert`],
    [`Escribe`, `Type`, `Escriu`, `Scrivi`, `Tapez`, `Tippe`],
    [`para confirmar`, `to confirm`, `per confirmar`, `per confermare`, `pour confirmer`, `zum Bestätigen`],
    [`Eliminar`, `Delete`, `Elimina`, `Elimina`, `Supprimer`, `Löschen`],
    [`Eliminando…`, `Deleting…`, `Eliminant…`, `Eliminazione…`, `Suppression…`, `Wird gelöscht…`],
    [`Persona eliminada`, `Person deleted`, `Persona eliminada`, `Persona eliminata`, `Personne supprimée`, `Person gelöscht`],
    [`Nueva categoría`, `New category`, `Nova categoria`, `Nuova categoria`, `Nouvelle catégorie`, `Neue Kategorie`],
    [`Color de la categoría`, `Category colour`, `Color de la categoria`, `Colore della categoria`, `Couleur de la catégorie`, `Farbe der Kategorie`],
    [`Todavía no tienes a nadie añadido.`, `You haven't added anyone yet.`, `Encara no has afegit ningú.`, `Non hai ancora aggiunto nessuno.`, `Vous n'avez encore ajouté personne.`, `Du hast noch niemanden hinzugefügt.`],
    [`Todavía no tienes categorías.`, `You don't have any categories yet.`, `Encara no tens categories.`, `Non hai ancora categorie.`, `Vous n'avez pas encore de catégories.`, `Du hast noch keine Kategorien.`],
    [`Crea la primera con el botón de abajo y así ordenarás tus documentos por tipo. Para crear más adelante, ve a Ajustes → "Categorías".`, `Create the first one with the button below and sort your documents by type. To create more later, go to Settings → "Categories".`, `Crea la primera amb el botó de sota i ordena així els teus documents per tipus. Per crear-ne més endavant, ves a Ajustos → "Categories".`, `Crea la prima con il pulsante qui sotto e ordina così i tuoi documenti per tipo. Per crearne altre in seguito, vai in Impostazioni → "Categorie".`, `Créez la première avec le bouton ci-dessous pour classer vos documents par type. Pour en créer d'autres plus tard, allez dans Paramètres → « Catégories ».`, `Lege die erste mit der Schaltfläche unten an und ordne so deine Dokumente nach Art. Um später weitere anzulegen, gehe zu Einstellungen → „Kategorien".`],
    [`Categoría renombrada`, `Category renamed`, `Categoria reanomenada`, `Categoria rinominata`, `Catégorie renommée`, `Kategorie umbenannt`],
    [`Categoría creada`, `Category created`, `Categoria creada`, `Categoria creata`, `Catégorie créée`, `Kategorie erstellt`],
    [`Categoría eliminada`, `Category deleted`, `Categoria eliminada`, `Categoria eliminata`, `Catégorie supprimée`, `Kategorie gelöscht`],
    [`Nueva persona`, `New person`, `Nova persona`, `Nuova persona`, `Nouvelle personne`, `Neue Person`],
    [`Nombre`, `Name`, `Nom`, `Nome`, `Nom`, `Name`],
    [`Persona añadida`, `Person added`, `Persona afegida`, `Persona aggiunta`, `Personne ajoutée`, `Person hinzugefügt`],

    // ---- fotos: recorte, giro y zoom
    [`Arrastra con un dedo para moverla, pellizca con dos para hacer zoom o girarla`, `Drag with one finger to move it, pinch with two to zoom or rotate it`, `Arrossega amb un dit per moure-la, pessiga amb dos per fer zoom o girar-la`, `Trascina con un dito per spostarla, pizzica con due dita per zoomare o ruotarla`, `Faites glisser avec un doigt pour la déplacer, pincez avec deux doigts pour zoomer ou la faire pivoter`, `Ziehe mit einem Finger, um es zu bewegen, kneife mit zwei Fingern zum Zoomen oder Drehen`],
    [`Usar esta foto`, `Use this photo`, `Fes servir aquesta foto`, `Usa questa foto`, `Utiliser cette photo`, `Dieses Foto verwenden`],
    [`Ajustar esquinas`, `Adjust corners`, `Ajusta les cantonades`, `Regola gli angoli`, `Ajuster les coins`, `Ecken anpassen`],
    [`Buscando los bordes del documento…`, `Looking for the document edges…`, `Cercant les vores del document…`, `Ricerca dei bordi del documento…`, `Recherche des bords du document…`, `Dokumentränder werden gesucht…`],
    [`Recortado automáticamente`, `Automatically cropped`, `Retallat automàticament`, `Ritagliato automaticamente`, `Recadré automatiquement`, `Automatisch zugeschnitten`],
    [`Ver foto original`, `View original photo`, `Veure la foto original`, `Vedi foto originale`, `Voir la photo originale`, `Original ansehen`],
    [`Recorte automático`, `Automatic crop`, `Retall automàtic`, `Ritaglio automatico`, `Recadrage automatique`, `Automatischer Zuschnitt`],
    [`No he encontrado los bordes`, `I couldn't find the edges`, `No he trobat les vores`, `Non ho trovato i bordi`, `Je n'ai pas trouvé les bords`, `Ich konnte die Ränder nicht finden`],
    [`Recorte automático no disponible ahora: recórtalo a mano`, `Automatic crop not available right now: crop it by hand`, `Retall automàtic no disponible ara: retalla-ho a mà`, `Ritaglio automatico non disponibile ora: ritaglia a mano`, `Recadrage automatique indisponible pour l'instant : recadrez-le à la main`, `Automatischer Zuschnitt gerade nicht verfügbar: schneide es von Hand zu`],
    [`Arrastra con un dedo para encajar el documento, pellizca con dos para hacer zoom o girarlo`, `Drag with one finger to fit the document, pinch with two to zoom or rotate it`, `Arrossega amb un dit per encaixar el document, pessiga amb dos per fer zoom o girar-lo`, `Trascina con un dito per inquadrare il documento, pizzica con due dita per zoomare o ruotarlo`, `Faites glisser avec un doigt pour ajuster le document, pincez avec deux doigts pour zoomer ou le faire pivoter`, `Ziehe mit einem Finger, um das Dokument einzupassen, kneife mit zwei Fingern zum Zoomen oder Drehen`],
    [`Usar este recorte`, `Use this crop`, `Fes servir aquest retall`, `Usa questo ritaglio`, `Utiliser ce recadrage`, `Diesen Zuschnitt verwenden`],
    [`Arrastra cada esquina hasta una esquina del documento`, `Drag each corner to a corner of the document`, `Arrossega cada cantonada fins a una cantonada del document`, `Trascina ogni angolo su un angolo del documento`, `Faites glisser chaque coin vers un coin du document`, `Ziehe jede Ecke auf eine Ecke des Dokuments`],
    [`Enderezar`, `Straighten`, `Endreça`, `Raddrizza`, `Redresser`, `Begradigen`],
    [`Enderezando…`, `Straightening…`, `Endreçant…`, `Raddrizzamento…`, `Redressement…`, `Wird begradigt…`],
    [`Las esquinas están demasiado juntas.`, `The corners are too close together.`, `Les cantonades són massa juntes.`, `Gli angoli sono troppo vicini tra loro.`, `Les coins sont trop rapprochés.`, `Die Ecken liegen zu nah beieinander.`],
    [`No se pudo enderezar la foto.`, `Could not straighten the photo.`, `No s'ha pogut endreçar la foto.`, `Impossibile raddrizzare la foto.`, `Impossible de redresser la photo.`, `Das Foto konnte nicht begradigt werden.`],
    [`Recorte automático no disponible`, `Automatic crop not available`, `Retall automàtic no disponible`, `Ritaglio automatico non disponibile`, `Recadrage automatique indisponible`, `Automatischer Zuschnitt nicht verfügbar`],

    // ---- pantalla de una persona y sus documentos
    [`Seleccionar documentos`, `Select documents`, `Selecciona documents`, `Seleziona documenti`, `Sélectionner des documents`, `Dokumente auswählen`],
    [`Elige varios para compartirlos`, `Pick several to share them`, `Tria'n diversos per compartir-los`, `Scegline diversi per condividerli`, `Choisissez-en plusieurs pour les partager`, `Wähle mehrere aus, um sie zu teilen`],
    [`Exportar copia`, `Export copy`, `Exporta una còpia`, `Esporta copia`, `Exporter une copie`, `Kopie exportieren`],
    [`Guarda sus documentos en un archivo`, `Save their documents to a file`, `Desa els seus documents en un fitxer`, `Salva i suoi documenti in un file`, `Enregistrer ses documents dans un fichier`, `Speichere ihre Dokumente in einer Datei`],
    [`Todos`, `All`, `Tots`, `Tutti`, `Tous`, `Alle`],
    [`Todavía no hay documentos aquí.`, `There are no documents here yet.`, `Encara no hi ha documents aquí.`, `Non ci sono ancora documenti qui.`, `Il n'y a pas encore de documents ici.`, `Hier gibt es noch keine Dokumente.`],
    [`Usa el botón de subir archivo, arriba, para añadir el primero.`, `Use the upload button at the top to add the first one.`, `Fes servir el botó de pujar fitxer, a dalt, per afegir el primer.`, `Usa il pulsante per caricare un file, in alto, per aggiungere il primo.`, `Utilisez le bouton d'import en haut pour ajouter le premier.`, `Nutze die Hochladen-Schaltfläche oben, um das erste hinzuzufügen.`],
    [`Todavía no hay documentos de esta categoría.`, `There are no documents in this category yet.`, `Encara no hi ha documents d'aquesta categoria.`, `Non ci sono ancora documenti in questa categoria.`, `Il n'y a pas encore de documents dans cette catégorie.`, `In dieser Kategorie gibt es noch keine Dokumente.`],
    [`Desplegar páginas`, `Show pages separately`, `Desplega les pàgines`, `Mostra le pagine separate`, `Afficher les pages séparément`, `Seiten einzeln anzeigen`],
    [`Cada página de un documento, en su propia ficha`, `Each page of a document on its own card`, `Cada pàgina d'un document, a la seva fitxa`, `Ogni pagina di un documento, nella sua scheda`, `Chaque page d'un document sur sa propre fiche`, `Jede Seite eines Dokuments auf eigener Karte`],
    [`Replegar páginas`, `Group pages together`, `Replega les pàgines`, `Raggruppa le pagine`, `Regrouper les pages`, `Seiten zusammenfassen`],
    [`Un documento de varias páginas, una sola ficha`, `A multi-page document on a single card`, `Un document de diverses pàgines, una sola fitxa`, `Un documento di più pagine, una sola scheda`, `Un document de plusieurs pages sur une seule fiche`, `Ein mehrseitiges Dokument auf einer Karte`],
    [`Caducado`, `Expired`, `Caducat`, `Scaduto`, `Expiré`, `Abgelaufen`],

    // ---- compartir
    [`Este móvil no permite compartir archivos desde el navegador.`, `This phone doesn't allow sharing files from the browser.`, `Aquest mòbil no permet compartir fitxers des del navegador.`, `Questo telefono non consente di condividere file dal browser.`, `Ce téléphone ne permet pas de partager des fichiers depuis le navigateur.`, `Dieses Handy erlaubt kein Teilen von Dateien über den Browser.`],
    [`Preparando…`, `Preparing…`, `Preparant…`, `Preparazione…`, `Préparation…`, `Wird vorbereitet…`],
    [`Estos archivos no se pueden compartir desde aquí.`, `These files can't be shared from here.`, `Aquests fitxers no es poden compartir des d'aquí.`, `Questi file non possono essere condivisi da qui.`, `Ces fichiers ne peuvent pas être partagés d'ici.`, `Diese Dateien können von hier aus nicht geteilt werden.`],
    [`No se pudo compartir.`, `Could not share.`, `No s'ha pogut compartir.`, `Impossibile condividere.`, `Impossible de partager.`, `Teilen fehlgeschlagen.`],
    [`Generando PDF…`, `Generating PDF…`, `Generant PDF…`, `Generazione del PDF…`, `Génération du PDF…`, `PDF wird erstellt…`],
    [`Este archivo no se puede compartir desde aquí.`, `This file can't be shared from here.`, `Aquest fitxer no es pot compartir des d'aquí.`, `Questo file non può essere condiviso da qui.`, `Ce fichier ne peut pas être partagé d'ici.`, `Diese Datei kann von hier aus nicht geteilt werden.`],
    [`No se pudo generar el PDF.`, `Could not generate the PDF.`, `No s'ha pogut generar el PDF.`, `Impossibile generare il PDF.`, `Impossible de générer le PDF.`, `PDF konnte nicht erstellt werden.`],

    // ---- visor, páginas y menús de un documento
    [`Abriendo…`, `Opening…`, `Obrint…`, `Apertura…`, `Ouverture…`, `Wird geöffnet…`],
    [`Documento PDF — ábrelo con el visor de tu móvil.`, `PDF document — open it with your phone's viewer.`, `Document PDF — obre'l amb el visor del teu mòbil.`, `Documento PDF — aprilo con il visualizzatore del telefono.`, `Document PDF — ouvrez-le avec la visionneuse de votre téléphone.`, `PDF-Dokument — öffne es mit dem Betrachter deines Handys.`],
    [`No se pudo cargar el documento. Comprueba tu conexión.`, `Could not load the document. Check your connection.`, `No s'ha pogut carregar el document. Comprova la connexió.`, `Impossibile caricare il documento. Controlla la connessione.`, `Impossible de charger le document. Vérifiez votre connexion.`, `Dokument konnte nicht geladen werden. Prüfe deine Verbindung.`],
    [`Nombre de la página`, `Page name`, `Nom de la pàgina`, `Nome della pagina`, `Nom de la page`, `Name der Seite`],
    [`Ej: Reverso, Página 2...`, `E.g. Back, Page 2...`, `Ex.: Revers, Pàgina 2...`, `Es.: Retro, Pagina 2...`, `Ex. : Verso, Page 2...`, `Z. B. Rückseite, Seite 2...`],
    [`Subiendo…`, `Uploading…`, `Pujant…`, `Caricamento…`, `Envoi en cours…`, `Wird hochgeladen…`],
    [`Página añadida`, `Page added`, `Pàgina afegida`, `Pagina aggiunta`, `Page ajoutée`, `Seite hinzugefügt`],
    [`No se pudo subir la página.`, `Could not upload the page.`, `No s'ha pogut pujar la pàgina.`, `Impossibile caricare la pagina.`, `Impossible d'envoyer la page.`, `Seite konnte nicht hochgeladen werden.`],
    [`Sin fecha de caducidad`, `No expiry date`, `Sense data de caducitat`, `Nessuna data di scadenza`, `Aucune date d'expiration`, `Kein Ablaufdatum`],
    [`Compartir esta página`, `Share this page`, `Comparteix aquesta pàgina`, `Condividi questa pagina`, `Partager cette page`, `Diese Seite teilen`],
    [`Envía la imagen por WhatsApp, correo…`, `Send the image via WhatsApp, email…`, `Envia la imatge per WhatsApp, correu…`, `Invia l'immagine tramite WhatsApp, email…`, `Envoyez l'image par WhatsApp, e-mail…`, `Sende das Bild per WhatsApp, E-Mail…`],
    [`Envía los archivos por WhatsApp, correo…`, `Send the files via WhatsApp, email…`, `Envia els fitxers per WhatsApp, correu…`, `Invia i file tramite WhatsApp, email…`, `Envoyez les fichiers par WhatsApp, e-mail…`, `Sende die Dateien per WhatsApp, E-Mail…`],
    [`Un solo PDF con todo lo elegido`, `A single PDF with everything selected`, `Un sol PDF amb tot el que has triat`, `Un unico PDF con tutto ciò che hai scelto`, `Un seul PDF avec toute la sélection`, `Ein einziges PDF mit allem Ausgewählten`],
    [`Compartir como PDF`, `Share as PDF`, `Comparteix com a PDF`, `Condividi come PDF`, `Partager en PDF`, `Als PDF teilen`],
    [`Un PDF solo con esta página`, `A PDF with just this page`, `Un PDF només amb aquesta pàgina`, `Un PDF con solo questa pagina`, `Un PDF avec seulement cette page`, `Ein PDF nur mit dieser Seite`],
    [`Un PDF con este documento`, `A PDF with this document`, `Un PDF amb aquest document`, `Un PDF con questo documento`, `Un PDF avec ce document`, `Ein PDF mit diesem Dokument`],
    [`Cambiar nombre de esta página`, `Rename this page`, `Canvia el nom d'aquesta pàgina`, `Rinomina questa pagina`, `Renommer cette page`, `Diese Seite umbenennen`],
    [`Cambiar nombre`, `Rename`, `Canvia el nom`, `Rinomina`, `Renommer`, `Umbenennen`],
    [`Se cambia también en las nubes`, `Also changed in the clouds`, `També es canvia als núvols`, `Viene cambiato anche nei cloud`, `Également modifié dans les clouds`, `Wird auch in den Clouds geändert`],
    [`Cambiar categoría`, `Change category`, `Canvia la categoria`, `Cambia categoria`, `Changer de catégorie`, `Kategorie ändern`],
    [`Añadir categoría`, `Add category`, `Afegeix una categoria`, `Aggiungi categoria`, `Ajouter une catégorie`, `Kategorie hinzufügen`],
    [`Cambiar fecha de caducidad`, `Change expiry date`, `Canvia la data de caducitat`, `Cambia data di scadenza`, `Changer la date d'expiration`, `Ablaufdatum ändern`],
    [`Añadir fecha de caducidad`, `Add expiry date`, `Afegeix una data de caducitat`, `Aggiungi data di scadenza`, `Ajouter une date d'expiration`, `Ablaufdatum hinzufügen`],
    [`Otra foto o PDF para este documento`, `Another photo or PDF for this document`, `Una altra foto o PDF per a aquest document`, `Un'altra foto o PDF per questo documento`, `Une autre photo ou un autre PDF pour ce document`, `Ein weiteres Foto oder PDF für dieses Dokument`],
    [`Eliminar esta página`, `Delete this page`, `Elimina aquesta pàgina`, `Elimina questa pagina`, `Supprimer cette page`, `Diese Seite löschen`],
    [`Eliminar documento`, `Delete document`, `Elimina el document`, `Elimina documento`, `Supprimer le document`, `Dokument löschen`],
    [`Quita solo esta página`, `Removes only this page`, `Treu només aquesta pàgina`, `Rimuove solo questa pagina`, `Retire uniquement cette page`, `Entfernt nur diese Seite`],
    [`Se elimina del móvil y de las nubes`, `Deleted from the phone and the clouds`, `S'elimina del mòbil i dels núvols`, `Viene eliminato dal telefono e dai cloud`, `Supprimé du téléphone et des clouds`, `Wird vom Handy und aus den Clouds gelöscht`],
    [`Compartir todas las páginas`, `Share all pages`, `Comparteix totes les pàgines`, `Condividi tutte le pagine`, `Partager toutes les pages`, `Alle Seiten teilen`],
    [`Envía las imágenes por WhatsApp, correo…`, `Send the images via WhatsApp, email…`, `Envia les imatges per WhatsApp, correu…`, `Invia le immagini tramite WhatsApp, email…`, `Envoyez les images par WhatsApp, e-mail…`, `Sende die Bilder per WhatsApp, E-Mail…`],
    [`Un solo PDF con todas las páginas`, `A single PDF with all the pages`, `Un sol PDF amb totes les pàgines`, `Un unico PDF con tutte le pagine`, `Un seul PDF avec toutes les pages`, `Ein einziges PDF mit allen Seiten`],
    [`Categoría actualizada`, `Category updated`, `Categoria actualitzada`, `Categoria aggiornata`, `Catégorie mise à jour`, `Kategorie aktualisiert`],
    [`Fecha de caducidad`, `Expiry date`, `Data de caducitat`, `Data di scadenza`, `Date d'expiration`, `Ablaufdatum`],
    [`Guardar`, `Save`, `Desa`, `Salva`, `Enregistrer`, `Speichern`],
    [`Quitar fecha de caducidad`, `Remove expiry date`, `Treu la data de caducitat`, `Rimuovi data di scadenza`, `Retirer la date d'expiration`, `Ablaufdatum entfernen`],
    [`Caducidad actualizada`, `Expiry updated`, `Caducitat actualitzada`, `Scadenza aggiornata`, `Expiration mise à jour`, `Ablaufdatum aktualisiert`],
    [`Fecha de caducidad eliminada`, `Expiry date removed`, `Data de caducitat eliminada`, `Data di scadenza rimossa`, `Date d'expiration supprimée`, `Ablaufdatum entfernt`],
    [`Se borrará también de tu Google Drive. Esta acción no se puede deshacer.`, `It will also be deleted from your Google Drive. This cannot be undone.`, `També s'esborrarà del teu Google Drive. Aquesta acció no es pot desfer.`, `Verrà eliminato anche dal tuo Google Drive. Questa azione non può essere annullata.`, `Il sera aussi supprimé de votre Google Drive. Cette action est irréversible.`, `Es wird auch aus deinem Google Drive gelöscht. Dies kann nicht rückgängig gemacht werden.`],
    [`Entiendo que se borrará para siempre`, `I understand it will be deleted forever`, `Entenc que s'esborrarà per sempre`, `Capisco che verrà eliminato per sempre`, `Je comprends qu'il sera supprimé définitivement`, `Ich verstehe, dass es dauerhaft gelöscht wird`],
    [`¿Seguro? Toca otra vez`, `Sure? Tap again`, `Segur? Torna a tocar`, `Sicuro? Tocca di nuovo`, `Sûr ? Appuyez à nouveau`, `Sicher? Tippe erneut`],
    [`Página eliminada`, `Page deleted`, `Pàgina eliminada`, `Pagina eliminata`, `Page supprimée`, `Seite gelöscht`],
    [`Documento eliminado`, `Document deleted`, `Document eliminat`, `Documento eliminato`, `Document supprimé`, `Dokument gelöscht`],
    [`No se pudo eliminar.`, `Could not delete.`, `No s'ha pogut eliminar.`, `Impossibile eliminare.`, `Impossible de supprimer.`, `Löschen fehlgeschlagen.`],

    // ---- subir un documento
    [`+ Añadir foto o PDF`, `+ Add photo or PDF`, `+ Afegeix una foto o PDF`, `+ Aggiungi foto o PDF`, `+ Ajouter une photo ou un PDF`, `+ Foto oder PDF hinzufügen`],
    [`Nombre del documento (así se guardará en Drive)`, `Document name (this is how it will be saved in Drive)`, `Nom del document (així es desarà a Drive)`, `Nome del documento (verrà salvato così su Drive)`, `Nom du document (c'est ainsi qu'il sera enregistré dans Drive)`, `Dokumentname (so wird er in Drive gespeichert)`],
    [`Fecha de caducidad (opcional)`, `Expiry date (optional)`, `Data de caducitat (opcional)`, `Data di scadenza (facoltativa)`, `Date d'expiration (facultatif)`, `Ablaufdatum (optional)`],
    [`Guardar en Drive`, `Save to Drive`, `Desa a Drive`, `Salva su Drive`, `Enregistrer dans Drive`, `In Drive speichern`],
    [`Documento guardado`, `Document saved`, `Document desat`, `Documento salvato`, `Document enregistré`, `Dokument gespeichert`],
    [`No se pudo subir el documento.`, `Could not upload the document.`, `No s'ha pogut pujar el document.`, `Impossibile caricare il documento.`, `Impossible d'envoyer le document.`, `Dokument konnte nicht hochgeladen werden.`],

    // ---- Ajustes, apariencia, estilo e idioma
    [`Automático, sigue a tu móvil`, `Automatic, follows your phone`, `Automàtic, segueix el teu mòbil`, `Automatico, segue il telefono`, `Automatique, suit votre téléphone`, `Automatisch, folgt deinem Handy`],
    [`Claro`, `Light`, `Clar`, `Chiaro`, `Clair`, `Hell`],
    [`Oscuro`, `Dark`, `Fosc`, `Scuro`, `Sombre`, `Dunkel`],
    [`Estilo`, `Style`, `Estil`, `Stile`, `Style`, `Stil`],
    [`Apariencia`, `Appearance`, `Aparença`, `Aspetto`, `Apparence`, `Erscheinungsbild`],
    [`Idioma`, `Language`, `Idioma`, `Lingua`, `Langue`, `Sprache`],
    [`Automático`, `Automatic`, `Automàtic`, `Automatico`, `Automatique`, `Automatisch`],
    [`Sigue el modo claro u oscuro de tu móvil`, `Follows your phone's light or dark mode`, `Segueix el mode clar o fosc del teu mòbil`, `Segue la modalità chiara o scura del telefono`, `Suit le mode clair ou sombre de votre téléphone`, `Folgt dem hellen oder dunklen Modus deines Handys`],
    [`Fondo claro, como un papel`, `Light background, like paper`, `Fons clar, com un paper`, `Sfondo chiaro, come la carta`, `Fond clair, comme du papier`, `Heller Hintergrund, wie Papier`],
    [`Fondo oscuro, más suave de noche`, `Dark background, softer at night`, `Fons fosc, més suau de nit`, `Sfondo scuro, più delicato di notte`, `Fond sombre, plus doux la nuit`, `Dunkler Hintergrund, angenehmer bei Nacht`],
    [`Personas`, `People`, `Persones`, `Persone`, `Personnes`, `Personen`],
    [`Añadir, renombrar, ordenar y eliminar`, `Add, rename, sort and delete`, `Afegeix, canvia el nom, ordena i elimina`, `Aggiungi, rinomina, ordina ed elimina`, `Ajouter, renommer, trier et supprimer`, `Hinzufügen, umbenennen, sortieren und löschen`],
    [`Categorías`, `Categories`, `Categories`, `Categorie`, `Catégories`, `Kategorien`],
    [`Los tipos de documento que usas`, `The types of document you use`, `Els tipus de document que fas servir`, `I tipi di documento che usi`, `Les types de documents que vous utilisez`, `Die Dokumentarten, die du verwendest`],
    [`Guarda todo en un archivo`, `Save everything to a file`, `Ho desa tot en un fitxer`, `Salva tutto in un file`, `Enregistrer le tout dans un fichier`, `Speichert alles in einer Datei`],
    [`Suma un archivo de copia a lo que ya tienes`, `Add a backup file to what you already have`, `Suma un fitxer de còpia al que ja tens`, `Aggiunge un file di backup a ciò che hai già`, `Ajoute un fichier de sauvegarde à ce que vous avez déjà`, `Fügt eine Sicherungsdatei zu dem hinzu, was du bereits hast`],
    [`Política de privacidad`, `Privacy policy`, `Política de privadesa`, `Informativa sulla privacy`, `Politique de confidentialité`, `Datenschutzerklärung`],
    [`Qué datos usa la app y dónde se guardan`, `What data the app uses and where it is stored`, `Quines dades fa servir l'app i on es desen`, `Quali dati usa l'app e dove vengono salvati`, `Quelles données l'app utilise et où elles sont stockées`, `Welche Daten die App nutzt und wo sie gespeichert werden`],
    [`Cerrar sesión`, `Sign out`, `Tanca la sessió`, `Esci`, `Se déconnecter`, `Abmelden`],
    [`Todavía no hay carpeta: haz antes una copia.`, `There is no folder yet: make a backup first.`, `Encara no hi ha carpeta: fes abans una còpia.`, `Non esiste ancora una cartella: fai prima un backup.`, `Il n'y a pas encore de dossier : faites d'abord une sauvegarde.`, `Es gibt noch keinen Ordner: erstelle zuerst eine Sicherung.`],
    [`¿Cerrar sesión?`, `Sign out?`, `Vols tancar la sessió?`, `Vuoi uscire?`, `Se déconnecter ?`, `Abmelden?`],
    [`Se desconectan todas las nubes y se borran los documentos y datos guardados en este móvil. En tus nubes se queda la última copia hecha.`, `All clouds are disconnected and the documents and data saved on this phone are deleted. The last backup made stays in your clouds.`, `Es desconnecten tots els núvols i s'esborren els documents i dades desats en aquest mòbil. Als teus núvols es queda l'última còpia feta.`, `Tutti i cloud vengono scollegati e i documenti e i dati salvati su questo telefono vengono cancellati. Nei tuoi cloud resta l'ultimo backup fatto.`, `Tous les clouds sont déconnectés et les documents et données enregistrés sur ce téléphone sont supprimés. La dernière sauvegarde reste dans vos clouds.`, `Alle Clouds werden getrennt und die auf diesem Handy gespeicherten Dokumente und Daten werden gelöscht. In deinen Clouds bleibt die letzte gemachte Sicherung erhalten.`],

    // ---- exportar e importar
    [`Antes de generarlo, la app se sincroniza`, `Before generating it, the app syncs`, `Abans de generar-lo, l'app se sincronitza`, `Prima di generarlo, l'app si sincronizza`, `Avant de le générer, l'appli se synchronise`, `Bevor sie erstellt wird, synchronisiert sich die App`],
    [`con las nubes que tengas conectadas: suma lo que haya en cada una y en este móvil, para que el archivo lo lleve todo.`, `with the clouds you have connected: it adds what is in each one and on this phone, so the file carries everything.`, `amb els núvols que tinguis connectats: suma el que hi hagi en cadascun i en aquest mòbil, perquè el fitxer ho porti tot.`, `con i cloud che hai collegato: somma ciò che c'è in ciascuno e su questo telefono, così il file porta con sé tutto.`, `avec les clouds que vous avez connectés : elle ajoute ce qu'il y a dans chacun et sur ce téléphone, pour que le fichier contienne tout.`, `mit den Clouds, die du verbunden hast: sie fügt zusammen, was in jeder und auf diesem Handy ist, damit die Datei alles enthält.`],
    [`El otro dispositivo solo necesita tener esta misma app instalada. Al abrir el archivo allí, todo lo que trae se sumará a lo que ya hubiera guardado, sin duplicar lo que ya esté y sin borrar nada.`, `The other device only needs to have this same app installed. When you open the file there, everything it contains will be added to what was already saved, without duplicating what's already there and without deleting anything.`, `L'altre dispositiu només necessita tenir aquesta mateixa app instal·lada. En obrir el fitxer allà, tot el que porta se sumarà al que ja hi hagués desat, sense duplicar el que ja hi sigui i sense esborrar res.`, `L'altro dispositivo deve solo avere questa stessa app installata. Aprendo il file lì, tutto ciò che contiene si aggiungerà a quanto già salvato, senza duplicare ciò che c'è già e senza cancellare nulla.`, `L'autre appareil doit simplement avoir cette même appli installée. En ouvrant le fichier là-bas, tout son contenu s'ajoutera à ce qui était déjà enregistré, sans dupliquer ce qui existe déjà et sans rien supprimer.`, `Das andere Gerät braucht nur dieselbe App installiert. Beim Öffnen der Datei dort wird alles, was sie enthält, zu dem bereits Gespeicherten hinzugefügt, ohne Vorhandenes zu duplizieren und ohne etwas zu löschen.`],
    [`Una vez se genere, lo envías al otro dispositivo por el medio que prefieras. Desde allí, solo hay que ir a Ajustes →`, `Once it's generated, send it to the other device by whichever means you prefer. From there, just go to Settings →`, `Un cop generat, l'envies a l'altre dispositiu pel mitjà que prefereixis. Des d'allà, només cal anar a Ajustos →`, `Una volta generato, invialo all'altro dispositivo con il mezzo che preferisci. Da lì basta andare in Impostazioni →`, `Une fois généré, envoyez-le à l'autre appareil par le moyen que vous préférez. De là, il suffit d'aller dans Paramètres →`, `Sobald sie erstellt ist, sende sie auf dem Weg, den du bevorzugst, an das andere Gerät. Dort musst du nur zu Einstellungen →`],
    [`"Importar copia"`, `"Import copy"`, `"Importa una còpia"`, `"Importa copia"`, `« Importer une copie »`, `„Kopie importieren" gehen`],
    [`(o pulsar "Importar archivo" en la pantalla inicial) y seleccionar ese archivo.`, `(or tap "Import file" on the start screen) and select that file.`, `(o prémer "Importa un fitxer" a la pantalla inicial) i seleccionar aquest fitxer.`, `(oppure toccare "Importa file" nella schermata iniziale) e selezionare quel file.`, `(ou appuyer sur « Importer un fichier » sur l'écran d'accueil) et sélectionner ce fichier.`, `(oder auf der Startseite auf „Datei importieren" tippen) und diese Datei auswählen.`],
    [`Generar archivo`, `Generate file`, `Genera el fitxer`, `Genera file`, `Générer le fichier`, `Datei erstellen`],
    [`No hay nada que exportar todavía.`, `There's nothing to export yet.`, `Encara no hi ha res per exportar.`, `Non c'è ancora nulla da esportare.`, `Il n'y a encore rien à exporter.`, `Es gibt noch nichts zu exportieren.`],
    [`Sincronizando con tus nubes…`, `Syncing with your clouds…`, `Sincronitzant amb els teus núvols…`, `Sincronizzazione con i tuoi cloud…`, `Synchronisation avec vos clouds…`, `Synchronisierung mit deinen Clouds…`],
    [`Generando el archivo, un momento…`, `Generating the file, one moment…`, `Generant el fitxer, un moment…`, `Generazione del file, un momento…`, `Génération du fichier, un instant…`, `Datei wird erstellt, einen Moment…`],
    [`No se pudo generar el archivo:`, `Could not generate the file:`, `No s'ha pogut generar el fitxer:`, `Impossibile generare il file:`, `Impossible de générer le fichier :`, `Datei konnte nicht erstellt werden:`],
    [`No se ha podido sincronizar con`, `Could not sync with`, `No s'ha pogut sincronitzar amb`, `Impossibile sincronizzare con`, `Impossible de synchroniser avec`, `Synchronisierung fehlgeschlagen mit`],
    [`. Si sigues, el archivo llevará lo que hay en este móvil y en las demás nubes, pero puede faltarle algo que solo esté en esa.`, `. If you continue, the file will contain what is on this phone and on the other clouds, but it may be missing something that is only in that one.`, `. Si continues, el fitxer portarà el que hi ha en aquest mòbil i en els altres núvols, però potser hi faltarà alguna cosa que només sigui en aquell.`, `. Se continui, il file conterrà ciò che c'è su questo telefono e negli altri cloud, ma potrebbe mancargli qualcosa che si trova solo in quello.`, `. Si vous continuez, le fichier contiendra ce qu'il y a sur ce téléphone et sur les autres clouds, mais il pourrait lui manquer quelque chose qui n'est que dans celui-là.`, `. Wenn du fortfährst, enthält die Datei das, was auf diesem Handy und den anderen Clouds ist, aber ihr könnte etwas fehlen, das nur in dieser einen ist.`],
    [`Exportar igualmente`, `Export anyway`, `Exporta igualment`, `Esporta comunque`, `Exporter quand même`, `Trotzdem exportieren`],
    [`Toca "Guardar" para descargarlo en este móvil, o "Compartir" para enviarlo directamente al otro dispositivo.`, `Tap "Save" to download it to this phone, or "Share" to send it straight to the other device.`, `Toca "Desa" per baixar-lo en aquest mòbil, o "Comparteix" per enviar-lo directament a l'altre dispositiu.`, `Tocca "Salva" per scaricarlo su questo telefono, o "Condividi" per inviarlo direttamente all'altro dispositivo.`, `Appuyez sur « Enregistrer » pour le télécharger sur ce téléphone, ou « Partager » pour l'envoyer directement à l'autre appareil.`, `Tippe auf „Speichern", um sie auf dieses Handy herunterzuladen, oder auf „Teilen", um sie direkt an das andere Gerät zu senden.`],
    [`Toca "Guardar" para descargarlo en este móvil y pasarlo después al otro dispositivo por donde prefieras.`, `Tap "Save" to download it to this phone and then pass it to the other device however you prefer.`, `Toca "Desa" per baixar-lo en aquest mòbil i passar-lo després a l'altre dispositiu pel mitjà que prefereixis.`, `Tocca "Salva" per scaricarlo su questo telefono e passarlo poi all'altro dispositivo come preferisci.`, `Appuyez sur « Enregistrer » pour le télécharger sur ce téléphone puis le transmettre à l'autre appareil comme vous préférez.`, `Tippe auf „Speichern", um sie auf dieses Handy herunterzuladen und sie danach auf dem Weg deiner Wahl an das andere Gerät weiterzugeben.`],
    [`Archivo generado`, `File generated`, `Fitxer generat`, `File generato`, `Fichier généré`, `Datei erstellt`],
    [`Ya está listo:`, `It's ready:`, `Ja és a punt:`, `È pronto:`, `C'est prêt :`, `Fertig:`],
    [`Guardar en el dispositivo`, `Save on the device`, `Desa al dispositiu`, `Salva sul dispositivo`, `Enregistrer sur l'appareil`, `Auf dem Gerät speichern`],
    [`Archivo guardado en Descargas.`, `File saved in Downloads.`, `Fitxer desat a Baixades.`, `File salvato in Download.`, `Fichier enregistré dans Téléchargements.`, `Datei in Downloads gespeichert.`],
    [`No se pudo compartir:`, `Could not share:`, `No s'ha pogut compartir:`, `Impossibile condividere:`, `Impossible de partager :`, `Teilen fehlgeschlagen:`],
    [`Elige el archivo`, `Choose the file`, `Tria el fitxer`, `Scegli il file`, `Choisissez le fichier`, `Wähle die Datei`],
    [`que te hayan pasado. Todo lo que traiga se sumará a lo que ya tienes guardado, sin duplicar lo que ya esté y sin borrar nada.`, `that you were given. Everything it contains will be added to what you already have saved, without duplicating what's already there and without deleting anything.`, `que t'hagin passat. Tot el que porti se sumarà al que ja tens desat, sense duplicar el que ja hi sigui i sense esborrar res.`, `che ti hanno passato. Tutto ciò che contiene si aggiungerà a quanto già salvato, senza duplicare ciò che c'è già e senza cancellare nulla.`, `qu'on vous a transmis. Tout son contenu s'ajoutera à ce que vous avez déjà enregistré, sans dupliquer ce qui existe déjà et sans rien supprimer.`, `die man dir gegeben hat. Alles, was sie enthält, wird zu dem hinzugefügt, was du bereits gespeichert hast, ohne Vorhandenes zu duplizieren und ohne etwas zu löschen.`],
    [`Elegir archivo`, `Choose file`, `Tria un fitxer`, `Scegli file`, `Choisir un fichier`, `Datei wählen`],
    [`Leyendo archivo…`, `Reading file…`, `Llegint el fitxer…`, `Lettura del file…`, `Lecture du fichier…`, `Datei wird gelesen…`],
    [`No había nada nuevo: ya lo tenías todo`, `There was nothing new: you already had everything`, `No hi havia res de nou: ja ho tenies tot`, `Non c'era nulla di nuovo: avevi già tutto`, `Il n'y avait rien de nouveau : vous aviez déjà tout`, `Es gab nichts Neues: du hattest schon alles`],
    [`No se pudo importar el archivo. ¿Seguro que es una copia válida?`, `Could not import the file. Are you sure it's a valid backup?`, `No s'ha pogut importar el fitxer. Estàs segur que és una còpia vàlida?`, `Impossibile importare il file. Sei sicuro che sia un backup valido?`, `Impossible d'importer le fichier. Êtes-vous sûr qu'il s'agit d'une sauvegarde valide ?`, `Datei konnte nicht importiert werden. Bist du sicher, dass es eine gültige Sicherung ist?`],
    [`No se pudo importar el archivo (o se importó solo en parte). ¿Seguro que es una copia válida?`, `Could not import the file (or it was only partly imported). Are you sure it's a valid backup?`, `No s'ha pogut importar el fitxer (o només s'ha importat en part). Estàs segur que és una còpia vàlida?`, `Impossibile importare il file (o è stato importato solo in parte). Sei sicuro che sia un backup valido?`, `Impossible d'importer le fichier (ou il n'a été importé qu'en partie). Êtes-vous sûr qu'il s'agit d'une sauvegarde valide ?`, `Datei konnte nicht importiert werden (oder wurde nur teilweise importiert). Bist du sicher, dass es eine gültige Sicherung ist?`],
  ];

  const CODIGO = [
    // ---- título de la página
    [`Documentación — tus documentos, en tu Drive`, `Documents — your documents, in your Drive`, `Documentació — els teus documents, al teu Drive`, `Documenti — i tuoi documenti, nel tuo Drive`, `Documents — vos documents, dans votre Drive`, `Dokumente — deine Dokumente, in deinem Drive`],
    [`Gestiona el DNI, carnet de conducir, tarjeta de discapacidad y otros documentos de tu familia. Todo se guarda en tu propio Google Drive, y también en el móvil para verlo sin conexión.`, `Manage the ID card, driving licence, disability card and other documents of your family. Everything is saved in your own Google Drive, and also on the phone so you can view it offline.`, `Gestiona el DNI, el carnet de conduir, la targeta de discapacitat i altres documents de la teva família. Tot es desa al teu propi Google Drive, i també al mòbil per veure'l sense connexió.`, `Gestisci carta d'identità, patente, tessera di invalidità e altri documenti della tua famiglia. Tutto viene salvato sul tuo Google Drive, e anche sul telefono per vederlo senza connessione.`, `Gérez la carte d'identité, le permis de conduire, la carte d'invalidité et les autres documents de votre famille. Tout est enregistré dans votre propre Google Drive, et aussi sur le téléphone pour le consulter hors connexion.`, `Verwalte Personalausweis, Führerschein, Schwerbehindertenausweis und andere Dokumente deiner Familie. Alles wird in deinem eigenen Google Drive gespeichert, und auch auf dem Handy, um es offline anzusehen.`],

    // ---- palabras sueltas para plurales
    [`persona`, `person`, `persona`, `persona`, `personne`, `Person`], [`personas`, `people`, `persones`, `persone`, `personnes`, `Personen`],
    [`documento`, `document`, `document`, `documento`, `document`, `Dokument`], [`documentos`, `documents`, `documents`, `documenti`, `documents`, `Dokumente`],
    [`página`, `page`, `pàgina`, `pagina`, `page`, `Seite`], [`páginas`, `pages`, `pàgines`, `pagine`, `pages`, `Seiten`],
    [`cosa`, `thing`, `cosa`, `cosa`, `chose`, `Sache`], [`cosas`, `things`, `coses`, `cose`, `choses`, `Sachen`],
    [`elemento`, `item`, `element`, `elemento`, `élément`, `Element`], [`elementos`, `items`, `elements`, `elementi`, `éléments`, `Elemente`],
    [`nube`, `cloud`, `núvol`, `cloud`, `cloud`, `Cloud`], [`nubes`, `clouds`, `núvols`, `cloud`, `clouds`, `Clouds`],
    [`cambio más reciente`, `more recent change`, `canvi més recent`, `modifica più recente`, `changement plus récent`, `neuere Änderung`], [`cambios más recientes`, `more recent changes`, `canvis més recents`, `modifiche più recenti`, `changements plus récents`, `neuere Änderungen`],

    // ---- nubes
    [`Copia de {nube} recuperada`, `Backup from {nube} restored`, `Còpia de {nube} recuperada`, `Copia da {nube} ripristinata`, `Copie de {nube} restaurée`, `Kopie von {nube} wiederhergestellt`],
    [`{nube} conectado`, `{nube} connected`, `{nube} connectat`, `{nube} collegato`, `{nube} connecté`, `{nube} verbunden`],
    [`{nube} desconectado`, `{nube} disconnected`, `{nube} desconnectat`, `{nube} scollegato`, `{nube} déconnecté`, `{nube} getrennt`],
    [`No se pudo conectar con {nube}.`, `Could not connect to {nube}.`, `No s'ha pogut connectar amb {nube}.`, `Impossibile connettersi a {nube}.`, `Impossible de se connecter à {nube}.`, `Verbindung zu {nube} fehlgeschlagen.`],
    [`No se completó la conexión con {nube}.`, `The connection with {nube} was not completed.`, `No s'ha completat la connexió amb {nube}.`, `La connessione con {nube} non è stata completata.`, `La connexion avec {nube} n'a pas abouti.`, `Die Verbindung mit {nube} wurde nicht abgeschlossen.`],
    [`Hay que volver a conectar {nube} (en Ajustes).`, `You need to reconnect {nube} (in Settings).`, `Cal tornar a connectar {nube} (a Ajustos).`, `Devi ricollegare {nube} (in Impostazioni).`, `Il faut reconnecter {nube} (dans Paramètres).`, `{nube} muss neu verbunden werden (unter Einstellungen).`],
    [`Se han traído a este móvil las novedades de {nube}`, `Updates from {nube} have been brought to this phone`, `S'han portat a aquest mòbil les novetats de {nube}`, `Le novità di {nube} sono state portate su questo telefono`, `Les nouveautés de {nube} ont été apportées sur ce téléphone`, `Neuigkeiten von {nube} wurden auf dieses Handy geholt`],
    [`{nube} había perdido un archivo: se ha vuelto a subir`, `{nube} had lost a file: it has been uploaded again`, `{nube} havia perdut un fitxer: s'ha tornat a pujar`, `{nube} aveva perso un file: è stato ricaricato`, `{nube} avait perdu un fichier : il a été renvoyé`, `{nube} hatte eine Datei verloren: sie wurde erneut hochgeladen`],
    [`{nube} había perdido {n} archivos: se han vuelto a subir`, `{nube} had lost {n} files: they have been uploaded again`, `{nube} havia perdut {n} fitxers: s'han tornat a pujar`, `{nube} aveva perso {n} file: sono stati ricaricati`, `{nube} avait perdu {n} fichiers : ils ont été renvoyés`, `{nube} hatte {n} Dateien verloren: sie wurden erneut hochgeladen`],
    [`Última sincronización automática: {cuando}`, `Last automatic sync: {cuando}`, `Última sincronització automàtica: {cuando}`, `Ultima sincronizzazione automatica: {cuando}`, `Dernière synchronisation automatique : {cuando}`, `Letzte automatische Synchronisierung: {cuando}`],
    [`todavía no`, `not yet`, `encara no`, `non ancora`, `pas encore`, `noch nicht`],
    [`{n} pendiente de copiar`, `{n} pending copy`, `{n} pendent de copiar`, `{n} in attesa di copia`, `{n} en attente de copie`, `{n} noch zu kopieren`],
    [`{n} pendientes de copiar`, `{n} pending copies`, `{n} pendents de copiar`, `{n} in attesa di copia`, `{n} en attente de copie`, `{n} noch zu kopieren`],
    [`Ver carpeta en {nube}`, `View folder in {nube}`, `Veure la carpeta a {nube}`, `Vedi cartella in {nube}`, `Voir le dossier dans {nube}`, `Ordner in {nube} ansehen`],
    [`{nubes} necesita atención.`, `{nubes} needs attention.`, `{nubes} necessita atenció.`, `{nubes} richiede attenzione.`, `{nubes} nécessite votre attention.`, `{nubes} benötigt Aufmerksamkeit.`],
    [`{nubes} necesitan atención.`, `{nubes} need attention.`, `{nubes} necessiten atenció.`, `{nubes} richiedono attenzione.`, `{nubes} nécessitent votre attention.`, `{nubes} benötigen Aufmerksamkeit.`],
    [`{a} y {b}`, `{a} and {b}`, `{a} i {b}`, `{a} e {b}`, `{a} et {b}`, `{a} und {b}`],
    [`{cosas} por enviar a tus nubes.`, `{cosas} to send to your clouds.`, `{cosas} per enviar als teus núvols.`, `{cosas} da inviare ai tuoi cloud.`, `{cosas} à envoyer vers vos clouds.`, `{cosas} zum Senden an deine Clouds.`],
    [`Sincronizado con {nubes}.`, `Synced with {nubes}.`, `Sincronitzat amb {nubes}.`, `Sincronizzato con {nubes}.`, `Synchronisé avec {nubes}.`, `Synchronisiert mit {nubes}.`],
    [`Hay {cosas} que todavía no se han copiado a la nube.`, `Not yet copied to the cloud: {cosas}.`, `Encara no copiat al núvol: {cosas}.`, `Ci sono {cosas} che non sono ancora state copiate nel cloud.`, `{cosas} n'ont pas encore été copiées sur le cloud.`, `Es gibt {cosas}, die noch nicht in die Cloud kopiert wurden.`],
    [`Se va a borrar todo esto: {resumen}.`, `All of this will be deleted: {resumen}.`, `S'esborrarà tot això: {resumen}.`, `Verrà cancellato tutto questo: {resumen}.`, `Tout ceci sera supprimé : {resumen}.`, `Folgendes wird gelöscht: {resumen}.`],
    [`{a}, {b} y {c}`, `{a}, {b} and {c}`, `{a}, {b} i {c}`, `{a}, {b} e {c}`, `{a}, {b} et {c}`, `{a}, {b} und {c}`],
    [`BORRAR`, `DELETE`, `ESBORRAR`, `ELIMINA`, `SUPPRIMER`, `LÖSCHEN`],

    // ---- personas y categorías
    [`¿Eliminar a {nombre}?`, `Delete {nombre}?`, `Vols eliminar {nombre}?`, `Eliminare {nombre}?`, `Supprimer {nombre} ?`, `{nombre} löschen?`],
    [`Se eliminarán también sus {n} documento de Drive. Esta acción no se puede deshacer.`, `Their {n} document will also be deleted from Drive. This cannot be undone.`, `També s'eliminarà el seu {n} document de Drive. Aquesta acció no es pot desfer.`, `Verrà eliminato anche il suo {n} documento da Drive. Questa azione non può essere annullata.`, `Son {n} document sera aussi supprimé de Drive. Cette action est irréversible.`, `Sein/Ihr {n} Dokument wird auch aus Drive gelöscht. Dies kann nicht rückgängig gemacht werden.`],
    [`Se eliminarán también sus {n} documentos de Drive. Esta acción no se puede deshacer.`, `Their {n} documents will also be deleted from Drive. This cannot be undone.`, `També s'eliminaran els seus {n} documents de Drive. Aquesta acció no es pot desfer.`, `Verranno eliminati anche i suoi {n} documenti da Drive. Questa azione non può essere annullata.`, `Ses {n} documents seront aussi supprimés de Drive. Cette action est irréversible.`, `Seine/Ihre {n} Dokumente werden auch aus Drive gelöscht. Dies kann nicht rückgängig gemacht werden.`],
    [`"{nombre}" es un nombre reservado, elige otro.`, `"{nombre}" is a reserved name, choose another.`, `"{nombre}" és un nom reservat, tria'n un altre.`, `"{nombre}" è un nome riservato, scegline un altro.`, `« {nombre} » est un nom réservé, choisissez-en un autre.`, `„{nombre}" ist ein reservierter Name, wähle einen anderen.`],
    [`¿Eliminar «{cat}»? Sus {n} documento pasarán a mostrarse como «{sin}».`, `Delete "{cat}"? Its {n} document will show as "{sin}".`, `Vols eliminar «{cat}»? El seu {n} document es mostrarà com a «{sin}».`, `Eliminare «{cat}»? Il suo {n} documento verrà mostrato come «{sin}».`, `Supprimer « {cat} » ? Son {n} document s'affichera comme « {sin} ».`, `„{cat}" löschen? Sein {n} Dokument wird als „{sin}" angezeigt.`],
    [`¿Eliminar «{cat}»? Sus {n} documentos pasarán a mostrarse como «{sin}».`, `Delete "{cat}"? Its {n} documents will show as "{sin}".`, `Vols eliminar «{cat}»? Els seus {n} documents es mostraran com a «{sin}».`, `Eliminare «{cat}»? I suoi {n} documenti verranno mostrati come «{sin}».`, `Supprimer « {cat} » ? Ses {n} documents s'afficheront comme « {sin} ».`, `„{cat}" löschen? Seine {n} Dokumente werden als „{sin}" angezeigt.`],
    [`¿Eliminar «{nombre}»?`, `Delete "{nombre}"?`, `Vols eliminar «{nombre}»?`, `Eliminare «{nombre}»?`, `Supprimer « {nombre} » ?`, `„{nombre}" löschen?`],

    // ---- documentos, avisos y notificaciones
    [`{n} seleccionado`, `{n} selected`, `{n} seleccionat`, `{n} selezionato`, `{n} sélectionné`, `{n} ausgewählt`],
    [`{n} seleccionados`, `{n} selected`, `{n} seleccionats`, `{n} selezionati`, `{n} sélectionnés`, `{n} ausgewählt`],
    [`{n} documentos`, `{n} documents`, `{n} documents`, `{n} documenti`, `{n} documents`, `{n} Dokumente`],
    [`{n} día`, `{n} day`, `{n} dia`, `{n} giorno`, `{n} jour`, `{n} Tag`],
    [`{n} días`, `{n} days`, `{n} dies`, `{n} giorni`, `{n} jours`, `{n} Tage`],
    [`Tiene {n} documento caducado`, `You have {n} expired document`, `Tens {n} document caducat`, `Hai {n} documento scaduto`, `Vous avez {n} document expiré`, `Du hast {n} abgelaufenes Dokument`],
    [`Tiene {n} documentos caducados`, `You have {n} expired documents`, `Tens {n} documents caducats`, `Hai {n} documenti scaduti`, `Vous avez {n} documents expirés`, `Du hast {n} abgelaufene Dokumente`],
    [`Tiene {n} documento a punto de caducar`, `You have {n} document about to expire`, `Tens {n} document a punt de caducar`, `Hai {n} documento in scadenza`, `Vous avez {n} document bientôt expiré`, `Du hast {n} bald ablaufendes Dokument`],
    [`Tiene {n} documentos a punto de caducar`, `You have {n} documents about to expire`, `Tens {n} documents a punt de caducar`, `Hai {n} documenti in scadenza`, `Vous avez {n} documents bientôt expirés`, `Du hast {n} bald ablaufende Dokumente`],
    [`Documento a punto de caducar`, `Document about to expire`, `Document a punt de caducar`, `Documento in scadenza`, `Document bientôt expiré`, `Dokument läuft bald ab`],
    [`{doc} de {persona} ha caducado.`, `{doc} of {persona} has expired.`, `{doc} de {persona} ha caducat.`, `{doc} di {persona} è scaduto.`, `{doc} de {persona} a expiré.`, `{doc} von {persona} ist abgelaufen.`],
    [`{doc} de {persona} caduca hoy.`, `{doc} of {persona} expires today.`, `{doc} de {persona} caduca avui.`, `{doc} di {persona} scade oggi.`, `{doc} de {persona} expire aujourd'hui.`, `{doc} von {persona} läuft heute ab.`],
    [`{doc} de {persona} caduca mañana.`, `{doc} of {persona} expires tomorrow.`, `{doc} de {persona} caduca demà.`, `{doc} di {persona} scade domani.`, `{doc} de {persona} expire demain.`, `{doc} von {persona} läuft morgen ab.`],
    [`{doc} de {persona} caduca en {n} días.`, `{doc} of {persona} expires in {n} days.`, `{doc} de {persona} caduca d'aquí a {n} dies.`, `{doc} di {persona} scade tra {n} giorni.`, `{doc} de {persona} expire dans {n} jours.`, `{doc} von {persona} läuft in {n} Tagen ab.`],
    [`{doc} ha caducado.`, `{doc} has expired.`, `{doc} ha caducat.`, `{doc} è scaduto.`, `{doc} a expiré.`, `{doc} ist abgelaufen.`],
    [`{doc} caduca hoy.`, `{doc} expires today.`, `{doc} caduca avui.`, `{doc} scade oggi.`, `{doc} expire aujourd'hui.`, `{doc} läuft heute ab.`],
    [`{doc} caduca mañana.`, `{doc} expires tomorrow.`, `{doc} caduca demà.`, `{doc} scade domani.`, `{doc} expire demain.`, `{doc} läuft morgen ab.`],
    [`{doc} caduca en {n} días.`, `{doc} expires in {n} days.`, `{doc} caduca d'aquí a {n} dies.`, `{doc} scade tra {n} giorni.`, `{doc} expire dans {n} jours.`, `{doc} läuft in {n} Tagen ab.`],
    [`Página {n}`, `Page {n}`, `Pàgina {n}`, `Pagina {n}`, `Page {n}`, `Seite {n}`],
    [`página {n}`, `page {n}`, `pàgina {n}`, `pagina {n}`, `page {n}`, `Seite {n}`],
    [`Caduca el {fecha}`, `Expires on {fecha}`, `Caduca el {fecha}`, `Scade il {fecha}`, `Expire le {fecha}`, `Läuft am {fecha} ab`],
    [`Versión {v}`, `Version {v}`, `Versió {v}`, `Versione {v}`, `Version {v}`, `Version {v}`],

    // ---- exportar e importar
    [`Exportar copia de {nombre}`, `Export copy of {nombre}`, `Exporta una còpia de {nombre}`, `Esporta copia di {nombre}`, `Exporter une copie de {nombre}`, `Kopie von {nombre} exportieren`],
    [`con los documentos de {nombre} (no con el resto de personas que tengas guardadas)`, `with the documents of {nombre} (not with the rest of the people you have saved)`, `amb els documents de {nombre} (no amb la resta de persones que tinguis desades)`, `con i documenti di {nombre} (non con il resto delle persone che hai salvato)`, `avec les documents de {nombre} (pas avec le reste des personnes que vous avez enregistrées)`, `mit den Dokumenten von {nombre} (nicht mit den anderen gespeicherten Personen)`],
    [`con todas las personas, categorías y documentos que tienes guardados`, `with all the people, categories and documents you have saved`, `amb totes les persones, categories i documents que tens desats`, `con tutte le persone, categorie e documenti che hai salvato`, `avec toutes les personnes, catégories et documents que vous avez enregistrés`, `mit allen gespeicherten Personen, Kategorien und Dokumenten`],
    [`Esto genera un único archivo, que se llamará {archivo}, {alcance}, listo para pasarlo a otro dispositivo.`, `This generates a single file, which will be named {archivo}, {alcance}, ready to hand over to another device.`, `Això genera un únic fitxer, que es dirà {archivo}, {alcance}, llest per passar-lo a un altre dispositiu.`, `Questo genera un unico file, che si chiamerà {archivo}, {alcance}, pronto per essere trasferito a un altro dispositivo.`, `Cela génère un seul fichier, nommé {archivo}, {alcance}, prêt à être transmis à un autre appareil.`, `Dies erstellt eine einzige Datei namens {archivo}, {alcance}, bereit für die Übertragung auf ein anderes Gerät.`],
    [`{nombre} todavía no tiene documentos guardados.`, `{nombre} doesn't have any saved documents yet.`, `{nombre} encara no té documents desats.`, `{nombre} non ha ancora documenti salvati.`, `{nombre} n'a pas encore de documents enregistrés.`, `{nombre} hat noch keine gespeicherten Dokumente.`],
    [`Revisando documento {i} de {total}…`, `Checking document {i} of {total}…`, `Revisant el document {i} de {total}…`, `Controllo del documento {i} di {total}…`, `Vérification du document {i} sur {total}…`, `Dokument {i} von {total} wird geprüft…`],
    [`Sumado: {a}, {b} y {c}`, `Added: {a}, {b} and {c}`, `Sumat: {a}, {b} i {c}`, `Aggiunti: {a}, {b} e {c}`, `Ajouté : {a}, {b} et {c}`, `Hinzugefügt: {a}, {b} und {c}`],
    [`; además, {cambios}`, `; also, {cambios}`, `; a més, {cambios}`, `; inoltre, {cambios}`, `; de plus, {cambios}`, `; außerdem {cambios}`],

    // ---- estilos
    [`Clásico`, `Classic`, `Clàssic`, `Classico`, `Classique`, `Klassisch`],
    [`Azul noche y terracota, el de siempre`, `Midnight blue and terracotta, as it has always been`, `Blau nit i terracota, el de sempre`, `Blu notte e terracotta, quello di sempre`, `Bleu nuit et terracotta, comme toujours`, `Nachtblau und Terrakotta, wie immer`],
    [`Pasaporte`, `Passport`, `Passaport`, `Passaporto`, `Passeport`, `Reisepass`],
    [`Burdeos y oro, esquinas rectas y letra de imprenta`, `Burgundy and gold, square corners and printed lettering`, `Burdeus i or, cantonades rectes i lletra d'impremta`, `Bordeaux e oro, angoli squadrati e caratteri da stampa`, `Bordeaux et or, coins carrés et lettrage d'imprimerie`, `Bordeauxrot und Gold, eckige Kanten und Druckschrift`],
    [`Carpeta`, `Folder`, `Carpeta`, `Cartella`, `Dossier`, `Ordner`],
    [`Cartulina de archivo, sello rojo y letra de máquina de escribir`, `Filing card, red stamp and typewriter lettering`, `Cartolina d'arxiu, segell vermell i lletra de màquina d'escriure`, `Cartoncino da archivio, timbro rosso e caratteri da macchina da scrivere`, `Fiche cartonnée, tampon rouge et lettrage de machine à écrire`, `Karteikarte, roter Stempel und Schreibmaschinenschrift`],
    [`Nórdico`, `Nordic`, `Nòrdic`, `Nordico`, `Nordique`, `Nordisch`],
    [`Blanco y aire, verde agua suave y formas redondeadas`, `White and air, soft aqua green and rounded shapes`, `Blanc i aire, verd aigua suau i formes arrodonides`, `Bianco e aria, verde acqua tenue e forme arrotondate`, `Blanc et air, vert d'eau doux et formes arrondies`, `Weiß und Luft, sanftes Aquagrün und runde Formen`],
    [`Contraste`, `Contrast`, `Contrast`, `Contrasto`, `Contraste`, `Kontrast`],
    [`Amarillo y negro, bordes gruesos y sombras duras`, `Yellow and black, thick borders and hard shadows`, `Groc i negre, vores gruixudes i ombres dures`, `Giallo e nero, bordi spessi e ombre nette`, `Jaune et noir, bordures épaisses et ombres dures`, `Gelb und Schwarz, dicke Ränder und harte Schatten`],
    [`Bosque`, `Forest`, `Bosc`, `Bosco`, `Forêt`, `Wald`],
    [`Verde hondo y albaricoque, formas de hoja`, `Deep green and apricot, leaf-shaped corners`, `Verd fons i albercoc, formes de fulla`, `Verde profondo e albicocca, forme a foglia`, `Vert profond et abricot, formes de feuille`, `Tiefgrün und Aprikose, blattförmige Ecken`],
    [`Píxeles`, `Pixels`, `Píxels`, `Pixel`, `Pixels`, `Pixel`],
    [`Videojuego de 8 bits: esquinas escalonadas, letra pixelada y colores retro (en claro, pantalla de Game Boy)`, `8-bit video game: stepped corners, pixel lettering and retro colours (in light mode, a Game Boy screen)`, `Videojoc de 8 bits: cantonades esglaonades, lletra pixelada i colors retro (en clar, pantalla de Game Boy)`, `Videogioco a 8 bit: angoli a gradini, caratteri pixelati e colori retrò (in chiaro, schermo da Game Boy)`, `Jeu vidéo 8 bits : coins en escalier, lettrage pixellisé et couleurs rétro (en clair, écran de Game Boy)`, `8-Bit-Videospiel: gestufte Ecken, Pixelschrift und Retro-Farben (im hellen Modus ein Game-Boy-Bildschirm)`],
    [`Neón`, `Neon`, `Neó`, `Neon`, `Néon`, `Neon`],
    [`Rótulos luminosos: contornos que brillan en rosa y turquesa sobre la noche`, `Glowing signs: outlines that shine pink and turquoise against the night`, `Rètols lluminosos: contorns que brillen en rosa i turquesa sobre la nit`, `Insegne luminose: contorni che brillano di rosa e turchese nella notte`, `Enseignes lumineuses : contours qui brillent en rose et turquoise dans la nuit`, `Leuchtreklamen: Umrisse, die in Pink und Türkis in der Nacht leuchten`],
    [`Chicle`, `Bubblegum`, `Xiclet`, `Gomma da masticare`, `Chewing-gum`, `Kaugummi`],
    [`Rosa chicle, menta, limón y celeste: todo redondo, gordito y de colorines`, `Bubblegum pink, mint, lemon and sky blue: all round, chubby and colourful`, `Rosa xiclet, menta, llimona i cel: tot rodó, rodonet i de colors`, `Rosa chewing-gum, menta, limone e azzurro: tutto rotondo, paffuto e colorato`, `Rose chewing-gum, menthe, citron et bleu ciel : tout rond, dodu et coloré`, `Kaugummi-Pink, Minze, Zitrone und Himmelblau: alles rund, pummelig und bunt`],
    [`Cómic`, `Comic`, `Còmic`, `Fumetto`, `Bande dessinée`, `Comic`],
    [`Blanco y negro de cómic: tinta gruesa, trama de puntitos y sombras duras`, `Black-and-white comic book: thick ink, halftone dots and hard shadows`, `Blanc i negre de còmic: tinta gruixuda, trama de puntets i ombres dures`, `Fumetto in bianco e nero: inchiostro spesso, retino a puntini e ombre nette`, `Bande dessinée en noir et blanc : encre épaisse, trame de points et ombres dures`, `Schwarz-Weiß-Comic: dicke Tusche, Rasterpunkte und harte Schatten`],
  ];

  function construir(lista, indice) {
    const salida = {};
    for (const entrada of lista) salida[entrada[0]] = entrada[indice];
    return salida;
  }
  // Índice de columna por idioma: 0 = es (no se usa: en castellano se devuelve la clave tal cual).
  const COLUMNA = { en: 1, ca: 2, it: 3, fr: 4, de: 5 };
  window.DICC_DOM = {}; window.DICC_CODIGO = {};
  for (const id of Object.keys(COLUMNA)) {
    window.DICC_DOM[id] = construir(DOM, COLUMNA[id]);
    window.DICC_CODIGO[id] = construir(CODIGO, COLUMNA[id]);
  }
})();
