// Diccionarios de la interfaz: castellano (el idioma en que está escrita la app), English y català.
// - DOM: textos que salen tal cual en pantalla (o en atributos como placeholder y aria-label). La
//   clave es el texto en castellano con los espacios normalizados. Una clave que termina en ":"
//   también vale como prefijo (p. ej. "No se pudo compartir:" + el motivo).
// - CODIGO: frases que el código compone con datos (nombres, números, plurales) y que se piden con
//   t('frase con {marcadores}', { marcador: valor }); y palabras sueltas que solo se usan así.
// Esto es SOLO la interfaz: los datos (nombres, categorías, copias, exportaciones) no se traducen.
(function () {
  const DOM = [
    // ---- atributos (aria-label, placeholder…)
    [`Volver`, `Back`, `Enrere`],
    [`Buscar documento`, `Search document`, `Cerca un document`],
    [`Ver en lista (categorías)`, `View as list (categories)`, `Veure en llista (categories)`],
    [`Ajustes`, `Settings`, `Ajustos`],
    [`Subir documento`, `Upload document`, `Puja un document`],
    [`Opciones de esta persona`, `Options for this person`, `Opcions d'aquesta persona`],
    [`Cerrar aviso`, `Close notice`, `Tanca l'avís`],
    [`Cancelar selección`, `Cancel selection`, `Cancel·la la selecció`],
    [`Ver en cuadrícula (personas)`, `View as grid (people)`, `Veure en quadrícula (persones)`],
    [`Buscar documento…`, `Search document…`, `Cerca un document…`],
    [`Cambiar imagen`, `Change image`, `Canvia la imatge`],
    [`Renombrar persona`, `Rename person`, `Canvia el nom de la persona`],
    [`Eliminar persona`, `Delete person`, `Elimina la persona`],
    [`Renombrar categoría`, `Rename category`, `Canvia el nom de la categoria`],
    [`Eliminar categoría`, `Delete category`, `Elimina la categoria`],
    [`Añadir nombre`, `Add name`, `Afegeix el nom`],
    [`Girar 90 grados a la izquierda`, `Rotate 90 degrees left`, `Gira 90 graus cap a l'esquerra`],
    [`Girar la foto`, `Rotate the photo`, `Gira la foto`],
    [`Girar 90 grados a la derecha`, `Rotate 90 degrees right`, `Gira 90 graus cap a la dreta`],
    [`Alejar`, `Zoom out`, `Allunya`],
    [`Zoom de la foto`, `Photo zoom`, `Zoom de la foto`],
    [`Acercar`, `Zoom in`, `Acosta`],
    [`Tiene documentos caducados o a punto de caducar`, `Has expired documents or ones about to expire`, `Té documents caducats o a punt de caducar`],
    [`Descargar`, `Download`, `Descarrega`],
    [`Opciones del documento`, `Document options`, `Opcions del document`],
    [`Añadir página`, `Add page`, `Afegeix una pàgina`],
    [`Ej: DNI`, `E.g. ID card`, `Ex.: DNI`],
    [`Nombre de esta página`, `Name of this page`, `Nom d'aquesta pàgina`],
    [`Quitar página`, `Remove page`, `Treu la pàgina`],
    [`Volver a Ajustes`, `Back to Settings`, `Torna a Ajustos`],
    [`Categoría`, `Category`, `Categoria`],

    // ---- bienvenida y nubes
    [`Documentación`, `Documents`, `Documentació`],
    [`DOCUMENTACIÓN`, `DOCUMENTS`, `DOCUMENTACIÓ`],
    [`El DNI, carnet de conducir, tarjeta de discapacidad y demás papeles de tu gente, siempre a mano. Tus documentos se guardan en este móvil.`, `ID cards, driving licences, disability cards and all the other paperwork of your people, always at hand. Your documents are stored on this phone.`, `El DNI, el carnet de conduir, la targeta de discapacitat i la resta de papers de la teva gent, sempre a mà. Els teus documents es guarden en aquest mòbil.`],
    [`Empezar de nuevo`, `Start fresh`, `Comença de nou`],
    [`Primera vez, sin nada guardado`, `First time, nothing saved yet`, `Primera vegada, sense res desat`],
    [`Iniciar sesión en tus nubes`, `Sign in to your clouds`, `Inicia la sessió als teus núvols`],
    [`Recuperar mi copia desde una nube`, `Restore my copy from a cloud`, `Recupera la meva còpia des d'un núvol`],
    [`Importar archivo`, `Import file`, `Importa un fitxer`],
    [`Cargar una copia (.txt) que exporté antes`, `Load a copy (.txt) that I exported earlier`, `Carrega una còpia (.txt) que vaig exportar abans`],
    [`Sin conectar ninguna nube, tus documentos solo estarán en este móvil.`, `Without connecting a cloud, your documents will only be on this phone.`, `Sense connectar cap núvol, els teus documents només estaran en aquest mòbil.`],
    [`Podrás conectar una cuando quieras en Ajustes → Copias de seguridad. Esta app no tiene servidor propio.`, `You can connect one whenever you like in Settings → Backups. This app has no server of its own.`, `Podràs connectar-ne un quan vulguis a Ajustos → Còpies de seguretat. Aquesta app no té servidor propi.`],
    [`¿Dónde está tu copia?`, `Where is your copy?`, `On és la teva còpia?`],
    [`Conéctala y se recuperará todo en este móvil.`, `Connect it and everything will be restored on this phone.`, `Connecta-la i es recuperarà tot en aquest mòbil.`],
    [`Conectar con Google Drive`, `Connect with Google Drive`, `Connecta amb Google Drive`],
    [`Conectar con Dropbox`, `Connect with Dropbox`, `Connecta amb Dropbox`],
    [`Instala la app en tu móvil para abrirla más rápido`, `Install the app on your phone to open it faster`, `Instal·la l'app al mòbil per obrir-la més ràpid`],
    [`Instalar`, `Install`, `Instal·la`],
    [`0 seleccionados`, `0 selected`, `0 seleccionats`],
    [`Compartir`, `Share`, `Comparteix`],
    [`No se pudo conectar con Google.`, `Could not connect to Google.`, `No s'ha pogut connectar amb Google.`],
    [`No se pudo completar la conexión.`, `The connection could not be completed.`, `No s'ha pogut completar la connexió.`],
    [`Google no está disponible ahora mismo.`, `Google is not available right now.`, `Google no està disponible ara mateix.`],
    [`Importando…`, `Importing…`, `Important…`],
    [`Preparando tus documentos…`, `Preparing your documents…`, `Preparant els teus documents…`],
    [`No se pudieron guardar los datos en este móvil (sin espacio).`, `Could not save the data on this phone (out of space).`, `No s'han pogut desar les dades en aquest mòbil (sense espai).`],
    [`Sin categoría`, `Uncategorised`, `Sense categoria`],
    [`Sin persona`, `No person`, `Sense persona`],

    // ---- aviso de "solo en este móvil"
    [`Solo en este móvil`, `Only on this phone`, `Només en aquest mòbil`],
    [`Tus documentos están guardados solo en este móvil. Si borras los datos de la app o cambias de móvil, se perderían. Conecta una nube (Google Drive o Dropbox) para tener copia de seguridad.`, `Your documents are stored only on this phone. If you clear the app data or change phone, they would be lost. Connect a cloud (Google Drive or Dropbox) to have a backup.`, `Els teus documents es guarden només en aquest mòbil. Si esborres les dades de l'app o canvies de mòbil, es perdrien. Connecta un núvol (Google Drive o Dropbox) per tenir còpia de seguretat.`],
    [`También puedes guardar una copia en un archivo desde`, `You can also save a copy to a file from`, `També pots desar una còpia en un fitxer des de`],
    [`Ajustes → Exportar copia`, `Settings → Export copy`, `Ajustos → Exporta una còpia`],
    [`, y recuperarla después con`, `, and restore it later with`, `, i recuperar-la després amb`],
    [`Importar copia`, `Import copy`, `Importa una còpia`],
    [`No volver a mostrar este aviso`, `Don't show this notice again`, `No tornis a mostrar aquest avís`],
    [`Conectar una nube`, `Connect a cloud`, `Connecta un núvol`],
    [`Cerrar`, `Close`, `Tanca`],

    // ---- estado de las nubes (Ajustes)
    [`Copiando…`, `Copying…`, `Copiant…`],
    [`Hay que volver a conectar`, `You need to reconnect`, `Cal tornar a connectar`],
    [`Sincronizado`, `Synced`, `Sincronitzat`],
    [`Conectar`, `Connect`, `Connecta`],
    [`Reconectar`, `Reconnect`, `Torna a connectar`],
    [`Desconectar`, `Disconnect`, `Desconnecta`],
    [`Sin conectar`, `Not connected`, `Sense connectar`],
    [`Ver carpeta`, `View folder`, `Veure la carpeta`],
    [`Conecta una nube para tener copia de seguridad.`, `Connect a cloud to have a backup.`, `Connecta un núvol per tenir còpia de seguretat.`],
    [`Revisa tus copias`, `Check your backups`, `Revisa les teves còpies`],
    [`Enviando los cambios a tus nubes.`, `Sending the changes to your clouds.`, `Enviant els canvis als teus núvols.`],
    [`Copia pendiente`, `Backup pending`, `Còpia pendent`],
    [`Todo a salvo`, `All safe`, `Tot a recer`],
    [`No hay ninguna nube conectada: no existe ninguna copia de seguridad.`, `No cloud is connected: there is no backup at all.`, `No hi ha cap núvol connectat: no existeix cap còpia de seguretat.`],

    // ---- cerrar sesión (tres avisos)
    [`Aviso 1 de 3`, `Warning 1 of 3`, `Avís 1 de 3`],
    [`Si cierras la sesión se borrarán de este móvil todos los documentos y sus archivos. No se podrán recuperar.`, `If you sign out, all documents and their files will be deleted from this phone. They cannot be recovered.`, `Si tanques la sessió s'esborraran d'aquest mòbil tots els documents i els seus fitxers. No es podran recuperar.`],
    [`Cancelar`, `Cancel`, `Cancel·la`],
    [`Guardar antes una copia en un archivo`, `First save a copy to a file`, `Desa abans una còpia en un fitxer`],
    [`Entiendo el riesgo, continuar`, `I understand the risk, continue`, `Entenc el risc, continua`],
    [`Aviso 2 de 3`, `Warning 2 of 3`, `Avís 2 de 3`],
    [`Esta es la única copia que existe. Si tienes un solo momento de duda, cancela y conecta una nube en Ajustes → Copias de seguridad.`, `This is the only copy that exists. If you have even a moment of doubt, cancel and connect a cloud in Settings → Backups.`, `Aquesta és l'única còpia que existeix. Si tens un sol moment de dubte, cancel·la i connecta un núvol a Ajustos → Còpies de seguretat.`],
    [`No, cancelar`, `No, cancel`, `No, cancel·la`],
    [`Sí, quiero continuar`, `Yes, I want to continue`, `Sí, vull continuar`],
    [`Aviso 3 de 3: último`, `Warning 3 of 3: last`, `Avís 3 de 3: l'últim`],
    [`Esto no se puede deshacer.`, `This cannot be undone.`, `Això no es pot desfer.`],
    [`Para confirmar, escribe`, `To confirm, type`, `Per confirmar, escriu`],
    [`en el recuadro.`, `in the box.`, `al quadre.`],
    [`Borrar todo y cerrar sesión`, `Delete everything and sign out`, `Esborra-ho tot i tanca la sessió`],

    // ---- búsqueda, personas y categorías
    [`Escribe el nombre de un documento para buscarlo entre todas las personas.`, `Type a document name to find it among all people.`, `Escriu el nom d'un document per trobar-lo entre totes les persones.`],
    [`No se ha encontrado ningún documento con ese nombre.`, `No document with that name was found.`, `No s'ha trobat cap document amb aquest nom.`],
    [`Todavía no tienes a nadie aquí.`, `You don't have anyone here yet.`, `Encara no tens ningú aquí.`],
    [`Ve a Ajustes → "Administrar personas" para crear la primera, o si ya tenías una copia, conéctala en Ajustes → "Copias de seguridad" (o usa "Importar copia" si te la pasaron en un archivo).`, `Go to Settings → "Manage people" to create the first one, or if you already had a copy, connect it in Settings → "Backups" (or use "Import copy" if it was given to you as a file).`, `Ves a Ajustos → "Administra persones" per crear-ne la primera, o si ja tenies una còpia, connecta-la a Ajustos → "Còpies de seguretat" (o fes servir "Importa una còpia" si te la van passar en un fitxer).`],
    [`Añadir`, `Add`, `Afegeix`],
    [`Hacer foto`, `Take photo`, `Fes una foto`],
    [`Galería`, `Gallery`, `Galeria`],
    [`Icono`, `Icon`, `Icona`],
    [`Ajustar foto`, `Adjust photo`, `Ajusta la foto`],
    [`Foto actualizada`, `Photo updated`, `Foto actualitzada`],
    [`Icono actualizado`, `Icon updated`, `Icona actualitzada`],
    [`Nombre actualizado`, `Name updated`, `Nom actualitzat`],
    [`Escribe`, `Type`, `Escriu`],
    [`para confirmar`, `to confirm`, `per confirmar`],
    [`Eliminar`, `Delete`, `Elimina`],
    [`Eliminando…`, `Deleting…`, `Eliminant…`],
    [`Persona eliminada`, `Person deleted`, `Persona eliminada`],
    [`Nueva categoría`, `New category`, `Nova categoria`],
    [`Eliminar categoría`, `Delete category`, `Elimina la categoria`],
    [`Categoría renombrada`, `Category renamed`, `Categoria reanomenada`],
    [`Categoría creada`, `Category created`, `Categoria creada`],
    [`Categoría eliminada`, `Category deleted`, `Categoria eliminada`],
    [`Nueva persona`, `New person`, `Nova persona`],
    [`Nombre`, `Name`, `Nom`],
    [`Persona añadida`, `Person added`, `Persona afegida`],

    // ---- fotos: recorte, giro y zoom
    [`Arrastra con un dedo para moverla, pellizca con dos para hacer zoom o girarla`, `Drag with one finger to move it, pinch with two to zoom or rotate it`, `Arrossega amb un dit per moure-la, pessiga amb dos per fer zoom o girar-la`],
    [`Usar esta foto`, `Use this photo`, `Fes servir aquesta foto`],
    [`Ajustar esquinas`, `Adjust corners`, `Ajusta les cantonades`],
    [`Buscando los bordes del documento…`, `Looking for the document edges…`, `Cercant les vores del document…`],
    [`Recortado automáticamente`, `Automatically cropped`, `Retallat automàticament`],
    [`Ver foto original`, `View original photo`, `Veure la foto original`],
    [`Recorte automático`, `Automatic crop`, `Retall automàtic`],
    [`No he encontrado los bordes`, `I couldn't find the edges`, `No he trobat les vores`],
    [`Recorte automático no disponible ahora: recórtalo a mano`, `Automatic crop not available right now: crop it by hand`, `Retall automàtic no disponible ara: retalla-ho a mà`],
    [`Arrastra con un dedo para encajar el documento, pellizca con dos para hacer zoom o girarlo`, `Drag with one finger to fit the document, pinch with two to zoom or rotate it`, `Arrossega amb un dit per encaixar el document, pessiga amb dos per fer zoom o girar-lo`],
    [`Usar este recorte`, `Use this crop`, `Fes servir aquest retall`],
    [`Arrastra cada esquina hasta una esquina del documento`, `Drag each corner to a corner of the document`, `Arrossega cada cantonada fins a una cantonada del document`],
    [`Enderezar`, `Straighten`, `Endreça`],
    [`Enderezando…`, `Straightening…`, `Endreçant…`],
    [`Las esquinas están demasiado juntas.`, `The corners are too close together.`, `Les cantonades són massa juntes.`],
    [`No se pudo enderezar la foto.`, `Could not straighten the photo.`, `No s'ha pogut endreçar la foto.`],
    [`Recorte automático no disponible`, `Automatic crop not available`, `Retall automàtic no disponible`],

    // ---- pantalla de una persona y sus documentos
    [`Seleccionar documentos`, `Select documents`, `Selecciona documents`],
    [`Elige varios para compartirlos`, `Pick several to share them`, `Tria'n diversos per compartir-los`],
    [`Exportar copia`, `Export copy`, `Exporta una còpia`],
    [`Guarda sus documentos en un archivo`, `Save their documents to a file`, `Desa els seus documents en un fitxer`],
    [`Todos`, `All`, `Tots`],
    [`Todavía no hay documentos aquí.`, `There are no documents here yet.`, `Encara no hi ha documents aquí.`],
    [`Usa el botón de subir archivo, arriba, para añadir el primero.`, `Use the upload button at the top to add the first one.`, `Fes servir el botó de pujar fitxer, a dalt, per afegir el primer.`],
    [`Todavía no hay documentos de esta categoría.`, `There are no documents in this category yet.`, `Encara no hi ha documents d'aquesta categoria.`],
    [`Caducado`, `Expired`, `Caducat`],

    // ---- compartir
    [`Este móvil no permite compartir archivos desde el navegador.`, `This phone doesn't allow sharing files from the browser.`, `Aquest mòbil no permet compartir fitxers des del navegador.`],
    [`Preparando…`, `Preparing…`, `Preparant…`],
    [`Estos archivos no se pueden compartir desde aquí.`, `These files can't be shared from here.`, `Aquests fitxers no es poden compartir des d'aquí.`],
    [`No se pudo compartir.`, `Could not share.`, `No s'ha pogut compartir.`],
    [`Generando PDF…`, `Generating PDF…`, `Generant PDF…`],
    [`Este archivo no se puede compartir desde aquí.`, `This file can't be shared from here.`, `Aquest fitxer no es pot compartir des d'aquí.`],
    [`No se pudo generar el PDF.`, `Could not generate the PDF.`, `No s'ha pogut generar el PDF.`],

    // ---- visor, páginas y menús de un documento
    [`Abriendo…`, `Opening…`, `Obrint…`],
    [`Documento PDF — ábrelo con el visor de tu móvil.`, `PDF document — open it with your phone's viewer.`, `Document PDF — obre'l amb el visor del teu mòbil.`],
    [`No se pudo cargar el documento. Comprueba tu conexión.`, `Could not load the document. Check your connection.`, `No s'ha pogut carregar el document. Comprova la connexió.`],
    [`Nombre de la página`, `Page name`, `Nom de la pàgina`],
    [`Ej: Reverso, Página 2...`, `E.g. Back, Page 2...`, `Ex.: Revers, Pàgina 2...`],
    [`Subiendo…`, `Uploading…`, `Pujant…`],
    [`Página añadida`, `Page added`, `Pàgina afegida`],
    [`No se pudo subir la página.`, `Could not upload the page.`, `No s'ha pogut pujar la pàgina.`],
    [`Sin fecha de caducidad`, `No expiry date`, `Sense data de caducitat`],
    [`Compartir esta página`, `Share this page`, `Comparteix aquesta pàgina`],
    [`Envía la imagen por WhatsApp, correo…`, `Send the image via WhatsApp, email…`, `Envia la imatge per WhatsApp, correu…`],
    [`Compartir como PDF`, `Share as PDF`, `Comparteix com a PDF`],
    [`Un PDF solo con esta página`, `A PDF with just this page`, `Un PDF només amb aquesta pàgina`],
    [`Un PDF con este documento`, `A PDF with this document`, `Un PDF amb aquest document`],
    [`Cambiar nombre de esta página`, `Rename this page`, `Canvia el nom d'aquesta pàgina`],
    [`Cambiar nombre`, `Rename`, `Canvia el nom`],
    [`Se cambia también en las nubes`, `Also changed in the clouds`, `També es canvia als núvols`],
    [`Cambiar categoría`, `Change category`, `Canvia la categoria`],
    [`Añadir categoría`, `Add category`, `Afegeix una categoria`],
    [`Cambiar fecha de caducidad`, `Change expiry date`, `Canvia la data de caducitat`],
    [`Añadir fecha de caducidad`, `Add expiry date`, `Afegeix una data de caducitat`],
    [`Otra foto o PDF para este documento`, `Another photo or PDF for this document`, `Una altra foto o PDF per a aquest document`],
    [`Eliminar esta página`, `Delete this page`, `Elimina aquesta pàgina`],
    [`Eliminar documento`, `Delete document`, `Elimina el document`],
    [`Quita solo esta página`, `Removes only this page`, `Treu només aquesta pàgina`],
    [`Se elimina del móvil y de las nubes`, `Deleted from the phone and the clouds`, `S'elimina del mòbil i dels núvols`],
    [`Compartir todas las páginas`, `Share all pages`, `Comparteix totes les pàgines`],
    [`Envía las imágenes por WhatsApp, correo…`, `Send the images via WhatsApp, email…`, `Envia les imatges per WhatsApp, correu…`],
    [`Un solo PDF con todas las páginas`, `A single PDF with all the pages`, `Un sol PDF amb totes les pàgines`],
    [`Categoría actualizada`, `Category updated`, `Categoria actualitzada`],
    [`Fecha de caducidad`, `Expiry date`, `Data de caducitat`],
    [`Guardar`, `Save`, `Desa`],
    [`Quitar fecha de caducidad`, `Remove expiry date`, `Treu la data de caducitat`],
    [`Caducidad actualizada`, `Expiry updated`, `Caducitat actualitzada`],
    [`Fecha de caducidad eliminada`, `Expiry date removed`, `Data de caducitat eliminada`],
    [`Se borrará también de tu Google Drive. Esta acción no se puede deshacer.`, `It will also be deleted from your Google Drive. This cannot be undone.`, `També s'esborrarà del teu Google Drive. Aquesta acció no es pot desfer.`],
    [`Entiendo que se borrará para siempre`, `I understand it will be deleted forever`, `Entenc que s'esborrarà per sempre`],
    [`¿Seguro? Toca otra vez`, `Sure? Tap again`, `Segur? Torna a tocar`],
    [`Página eliminada`, `Page deleted`, `Pàgina eliminada`],
    [`Documento eliminado`, `Document deleted`, `Document eliminat`],
    [`No se pudo eliminar.`, `Could not delete.`, `No s'ha pogut eliminar.`],

    // ---- subir un documento
    [`+ Añadir foto o PDF`, `+ Add photo or PDF`, `+ Afegeix una foto o PDF`],
    [`Nombre del documento (así se guardará en Drive)`, `Document name (this is how it will be saved in Drive)`, `Nom del document (així es desarà a Drive)`],
    [`Fecha de caducidad (opcional)`, `Expiry date (optional)`, `Data de caducitat (opcional)`],
    [`Guardar en Drive`, `Save to Drive`, `Desa a Drive`],
    [`Documento guardado`, `Document saved`, `Document desat`],
    [`No se pudo subir el documento.`, `Could not upload the document.`, `No s'ha pogut pujar el document.`],

    // ---- Ajustes, apariencia, estilo e idioma
    [`Automático, sigue a tu móvil`, `Automatic, follows your phone`, `Automàtic, segueix el teu mòbil`],
    [`Claro`, `Light`, `Clar`],
    [`Oscuro`, `Dark`, `Fosc`],
    [`Estilo`, `Style`, `Estil`],
    [`Apariencia`, `Appearance`, `Aparença`],
    [`Idioma`, `Language`, `Idioma`],
    [`Automático`, `Automatic`, `Automàtic`],
    [`Sigue el modo claro u oscuro de tu móvil`, `Follows your phone's light or dark mode`, `Segueix el mode clar o fosc del teu mòbil`],
    [`Fondo claro, como un papel`, `Light background, like paper`, `Fons clar, com un paper`],
    [`Fondo oscuro, más suave de noche`, `Dark background, softer at night`, `Fons fosc, més suau de nit`],
    [`Personas`, `People`, `Persones`],
    [`Añadir, renombrar, ordenar y eliminar`, `Add, rename, sort and delete`, `Afegeix, canvia el nom, ordena i elimina`],
    [`Categorías`, `Categories`, `Categories`],
    [`Los tipos de documento que usas`, `The types of document you use`, `Els tipus de document que fas servir`],
    [`Guarda todo en un archivo`, `Save everything to a file`, `Ho desa tot en un fitxer`],
    [`Suma un archivo de copia a lo que ya tienes`, `Add a backup file to what you already have`, `Suma un fitxer de còpia al que ja tens`],
    [`Cerrar sesión`, `Sign out`, `Tanca la sessió`],
    [`Todavía no hay carpeta: haz antes una copia.`, `There is no folder yet: make a backup first.`, `Encara no hi ha carpeta: fes abans una còpia.`],
    [`¿Cerrar sesión?`, `Sign out?`, `Vols tancar la sessió?`],
    [`Se desconectan todas las nubes y se borran los documentos y datos guardados en este móvil. En tus nubes se queda la última copia hecha.`, `All clouds are disconnected and the documents and data saved on this phone are deleted. The last backup made stays in your clouds.`, `Es desconnecten tots els núvols i s'esborren els documents i dades desats en aquest mòbil. Als teus núvols es queda l'última còpia feta.`],

    // ---- exportar e importar
    [`Antes de generarlo, la app se sincroniza`, `Before generating it, the app syncs`, `Abans de generar-lo, l'app se sincronitza`],
    [`con las nubes que tengas conectadas: suma lo que haya en cada una y en este móvil, para que el archivo lo lleve todo.`, `with the clouds you have connected: it adds what is in each one and on this phone, so the file carries everything.`, `amb els núvols que tinguis connectats: suma el que hi hagi en cadascun i en aquest mòbil, perquè el fitxer ho porti tot.`],
    [`El otro dispositivo solo necesita tener esta misma app instalada. Al abrir el archivo allí, todo lo que trae se sumará a lo que ya hubiera guardado, sin duplicar lo que ya esté y sin borrar nada.`, `The other device only needs to have this same app installed. When you open the file there, everything it contains will be added to what was already saved, without duplicating what's already there and without deleting anything.`, `L'altre dispositiu només necessita tenir aquesta mateixa app instal·lada. En obrir el fitxer allà, tot el que porta se sumarà al que ja hi hagués desat, sense duplicar el que ja hi sigui i sense esborrar res.`],
    [`Una vez se genere, lo envías al otro dispositivo por el medio que prefieras. Desde allí, solo hay que ir a Ajustes →`, `Once it's generated, send it to the other device by whichever means you prefer. From there, just go to Settings →`, `Un cop generat, l'envies a l'altre dispositiu pel mitjà que prefereixis. Des d'allà, només cal anar a Ajustos →`],
    [`"Importar copia"`, `"Import copy"`, `"Importa una còpia"`],
    [`(o pulsar "Importar archivo" en la pantalla inicial) y seleccionar ese archivo.`, `(or tap "Import file" on the start screen) and select that file.`, `(o prémer "Importa un fitxer" a la pantalla inicial) i seleccionar aquest fitxer.`],
    [`Generar archivo`, `Generate file`, `Genera el fitxer`],
    [`No hay nada que exportar todavía.`, `There's nothing to export yet.`, `Encara no hi ha res per exportar.`],
    [`Sincronizando con tus nubes…`, `Syncing with your clouds…`, `Sincronitzant amb els teus núvols…`],
    [`Generando el archivo, un momento…`, `Generating the file, one moment…`, `Generant el fitxer, un moment…`],
    [`No se pudo generar el archivo:`, `Could not generate the file:`, `No s'ha pogut generar el fitxer:`],
    [`No se ha podido sincronizar con`, `Could not sync with`, `No s'ha pogut sincronitzar amb`],
    [`. Si sigues, el archivo llevará lo que hay en este móvil y en las demás nubes, pero puede faltarle algo que solo esté en esa.`, `. If you continue, the file will contain what is on this phone and on the other clouds, but it may be missing something that is only in that one.`, `. Si continues, el fitxer portarà el que hi ha en aquest mòbil i en els altres núvols, però potser hi faltarà alguna cosa que només sigui en aquell.`],
    [`Exportar igualmente`, `Export anyway`, `Exporta igualment`],
    [`Toca "Guardar" para descargarlo en este móvil, o "Compartir" para enviarlo directamente al otro dispositivo.`, `Tap "Save" to download it to this phone, or "Share" to send it straight to the other device.`, `Toca "Desa" per baixar-lo en aquest mòbil, o "Comparteix" per enviar-lo directament a l'altre dispositiu.`],
    [`Toca "Guardar" para descargarlo en este móvil y pasarlo después al otro dispositivo por donde prefieras.`, `Tap "Save" to download it to this phone and then pass it to the other device however you prefer.`, `Toca "Desa" per baixar-lo en aquest mòbil i passar-lo després a l'altre dispositiu pel mitjà que prefereixis.`],
    [`Archivo generado`, `File generated`, `Fitxer generat`],
    [`Ya está listo:`, `It's ready:`, `Ja és a punt:`],
    [`Guardar en el dispositivo`, `Save on the device`, `Desa al dispositiu`],
    [`Archivo guardado en Descargas.`, `File saved in Downloads.`, `Fitxer desat a Baixades.`],
    [`No se pudo compartir:`, `Could not share:`, `No s'ha pogut compartir:`],
    [`Elige el archivo`, `Choose the file`, `Tria el fitxer`],
    [`que te hayan pasado. Todo lo que traiga se sumará a lo que ya tienes guardado, sin duplicar lo que ya esté y sin borrar nada.`, `that you were given. Everything it contains will be added to what you already have saved, without duplicating what's already there and without deleting anything.`, `que t'hagin passat. Tot el que porti se sumarà al que ja tens desat, sense duplicar el que ja hi sigui i sense esborrar res.`],
    [`Elegir archivo`, `Choose file`, `Tria un fitxer`],
    [`Leyendo archivo…`, `Reading file…`, `Llegint el fitxer…`],
    [`No había nada nuevo: ya lo tenías todo`, `There was nothing new: you already had everything`, `No hi havia res de nou: ja ho tenies tot`],
    [`No se pudo importar el archivo. ¿Seguro que es una copia válida?`, `Could not import the file. Are you sure it's a valid backup?`, `No s'ha pogut importar el fitxer. Estàs segur que és una còpia vàlida?`],
    [`No se pudo importar el archivo (o se importó solo en parte). ¿Seguro que es una copia válida?`, `Could not import the file (or it was only partly imported). Are you sure it's a valid backup?`, `No s'ha pogut importar el fitxer (o només s'ha importat en part). Estàs segur que és una còpia vàlida?`],
  ];

  const CODIGO = [
    // ---- título de la página
    [`Documentación — tus documentos, en tu Drive`, `Documents — your documents, in your Drive`, `Documentació — els teus documents, al teu Drive`],
    [`Gestiona el DNI, carnet de conducir, tarjeta de discapacidad y otros documentos de tu familia. Todo se guarda en tu propio Google Drive, y también en el móvil para verlo sin conexión.`, `Manage the ID card, driving licence, disability card and other documents of your family. Everything is saved in your own Google Drive, and also on the phone so you can view it offline.`, `Gestiona el DNI, el carnet de conduir, la targeta de discapacitat i altres documents de la teva família. Tot es desa al teu propi Google Drive, i també al mòbil per veure'l sense connexió.`],

    // ---- palabras sueltas para plurales
    [`persona`, `person`, `persona`], [`personas`, `people`, `persones`],
    [`documento`, `document`, `document`], [`documentos`, `documents`, `documents`],
    [`página`, `page`, `pàgina`], [`páginas`, `pages`, `pàgines`],
    [`cosa`, `thing`, `cosa`], [`cosas`, `things`, `coses`],
    [`elemento`, `item`, `element`], [`elementos`, `items`, `elements`],
    [`nube`, `cloud`, `núvol`], [`nubes`, `clouds`, `núvols`],
    [`cambio más reciente`, `more recent change`, `canvi més recent`], [`cambios más recientes`, `more recent changes`, `canvis més recents`],

    // ---- nubes
    [`Copia de {nube} recuperada`, `Backup from {nube} restored`, `Còpia de {nube} recuperada`],
    [`{nube} conectado`, `{nube} connected`, `{nube} connectat`],
    [`{nube} desconectado`, `{nube} disconnected`, `{nube} desconnectat`],
    [`No se pudo conectar con {nube}.`, `Could not connect to {nube}.`, `No s'ha pogut connectar amb {nube}.`],
    [`No se completó la conexión con {nube}.`, `The connection with {nube} was not completed.`, `No s'ha completat la connexió amb {nube}.`],
    [`Hay que volver a conectar {nube} (en Ajustes).`, `You need to reconnect {nube} (in Settings).`, `Cal tornar a connectar {nube} (a Ajustos).`],
    [`Se han traído a este móvil las novedades de {nube}`, `Updates from {nube} have been brought to this phone`, `S'han portat a aquest mòbil les novetats de {nube}`],
    [`{nube} había perdido un archivo: se ha vuelto a subir`, `{nube} had lost a file: it has been uploaded again`, `{nube} havia perdut un fitxer: s'ha tornat a pujar`],
    [`{nube} había perdido {n} archivos: se han vuelto a subir`, `{nube} had lost {n} files: they have been uploaded again`, `{nube} havia perdut {n} fitxers: s'han tornat a pujar`],
    [`Última sincronización automática: {cuando}`, `Last automatic sync: {cuando}`, `Última sincronització automàtica: {cuando}`],
    [`todavía no`, `not yet`, `encara no`],
    [`{n} pendiente de copiar`, `{n} pending copy`, `{n} pendent de copiar`],
    [`{n} pendientes de copiar`, `{n} pending copies`, `{n} pendents de copiar`],
    [`Ver carpeta en {nube}`, `View folder in {nube}`, `Veure la carpeta a {nube}`],
    [`{nubes} necesita atención.`, `{nubes} needs attention.`, `{nubes} necessita atenció.`],
    [`{nubes} necesitan atención.`, `{nubes} need attention.`, `{nubes} necessiten atenció.`],
    [`{a} y {b}`, `{a} and {b}`, `{a} i {b}`],
    [`{cosas} por enviar a tus nubes.`, `{cosas} to send to your clouds.`, `{cosas} per enviar als teus núvols.`],
    [`Sincronizado con {nubes}.`, `Synced with {nubes}.`, `Sincronitzat amb {nubes}.`],
    [`Hay {cosas} que todavía no se han copiado a la nube.`, `Not yet copied to the cloud: {cosas}.`, `Encara no copiat al núvol: {cosas}.`],
    [`Se va a borrar todo esto: {resumen}.`, `All of this will be deleted: {resumen}.`, `S'esborrarà tot això: {resumen}.`],
    [`{a}, {b} y {c}`, `{a}, {b} and {c}`, `{a}, {b} i {c}`],
    [`BORRAR`, `DELETE`, `ESBORRAR`],

    // ---- personas y categorías
    [`¿Eliminar a {nombre}?`, `Delete {nombre}?`, `Vols eliminar {nombre}?`],
    [`Se eliminarán también sus {n} documento de Drive. Esta acción no se puede deshacer.`, `Their {n} document will also be deleted from Drive. This cannot be undone.`, `També s'eliminarà el seu {n} document de Drive. Aquesta acció no es pot desfer.`],
    [`Se eliminarán también sus {n} documentos de Drive. Esta acción no se puede deshacer.`, `Their {n} documents will also be deleted from Drive. This cannot be undone.`, `També s'eliminaran els seus {n} documents de Drive. Aquesta acció no es pot desfer.`],
    [`"{nombre}" es un nombre reservado, elige otro.`, `"{nombre}" is a reserved name, choose another.`, `"{nombre}" és un nom reservat, tria'n un altre.`],
    [`¿Eliminar «{cat}»? Sus {n} documento pasarán a mostrarse como «{sin}».`, `Delete "{cat}"? Its {n} document will show as "{sin}".`, `Vols eliminar «{cat}»? El seu {n} document es mostrarà com a «{sin}».`],
    [`¿Eliminar «{cat}»? Sus {n} documentos pasarán a mostrarse como «{sin}».`, `Delete "{cat}"? Its {n} documents will show as "{sin}".`, `Vols eliminar «{cat}»? Els seus {n} documents es mostraran com a «{sin}».`],
    [`¿Eliminar «{nombre}»?`, `Delete "{nombre}"?`, `Vols eliminar «{nombre}»?`],

    // ---- documentos, avisos y notificaciones
    [`{n} seleccionado`, `{n} selected`, `{n} seleccionat`],
    [`{n} seleccionados`, `{n} selected`, `{n} seleccionats`],
    [`{n} documentos`, `{n} documents`, `{n} documents`],
    [`{n} día`, `{n} day`, `{n} dia`],
    [`{n} días`, `{n} days`, `{n} dies`],
    [`Tiene {n} documento caducado`, `You have {n} expired document`, `Tens {n} document caducat`],
    [`Tiene {n} documentos caducados`, `You have {n} expired documents`, `Tens {n} documents caducats`],
    [`Tiene {n} documento a punto de caducar`, `You have {n} document about to expire`, `Tens {n} document a punt de caducar`],
    [`Tiene {n} documentos a punto de caducar`, `You have {n} documents about to expire`, `Tens {n} documents a punt de caducar`],
    [`Documento a punto de caducar`, `Document about to expire`, `Document a punt de caducar`],
    [`{doc} de {persona} ha caducado.`, `{doc} of {persona} has expired.`, `{doc} de {persona} ha caducat.`],
    [`{doc} de {persona} caduca hoy.`, `{doc} of {persona} expires today.`, `{doc} de {persona} caduca avui.`],
    [`{doc} de {persona} caduca mañana.`, `{doc} of {persona} expires tomorrow.`, `{doc} de {persona} caduca demà.`],
    [`{doc} de {persona} caduca en {n} días.`, `{doc} of {persona} expires in {n} days.`, `{doc} de {persona} caduca d'aquí a {n} dies.`],
    [`{doc} ha caducado.`, `{doc} has expired.`, `{doc} ha caducat.`],
    [`{doc} caduca hoy.`, `{doc} expires today.`, `{doc} caduca avui.`],
    [`{doc} caduca mañana.`, `{doc} expires tomorrow.`, `{doc} caduca demà.`],
    [`{doc} caduca en {n} días.`, `{doc} expires in {n} days.`, `{doc} caduca d'aquí a {n} dies.`],
    [`Página {n}`, `Page {n}`, `Pàgina {n}`],
    [`página {n}`, `page {n}`, `pàgina {n}`],
    [`Caduca el {fecha}`, `Expires on {fecha}`, `Caduca el {fecha}`],
    [`Versión {v}`, `Version {v}`, `Versió {v}`],

    // ---- exportar e importar
    [`Exportar copia de {nombre}`, `Export copy of {nombre}`, `Exporta una còpia de {nombre}`],
    [`con los documentos de {nombre} (no con el resto de personas que tengas guardadas)`, `with the documents of {nombre} (not with the rest of the people you have saved)`, `amb els documents de {nombre} (no amb la resta de persones que tinguis desades)`],
    [`con todas las personas, categorías y documentos que tienes guardados`, `with all the people, categories and documents you have saved`, `amb totes les persones, categories i documents que tens desats`],
    [`Esto genera un único archivo, que se llamará {archivo}, {alcance}, listo para pasarlo a otro dispositivo.`, `This generates a single file, which will be named {archivo}, {alcance}, ready to hand over to another device.`, `Això genera un únic fitxer, que es dirà {archivo}, {alcance}, llest per passar-lo a un altre dispositiu.`],
    [`{nombre} todavía no tiene documentos guardados.`, `{nombre} doesn't have any saved documents yet.`, `{nombre} encara no té documents desats.`],
    [`Revisando documento {i} de {total}…`, `Checking document {i} of {total}…`, `Revisant el document {i} de {total}…`],
    [`Sumado: {a}, {b} y {c}`, `Added: {a}, {b} and {c}`, `Sumat: {a}, {b} i {c}`],
    [`; además, {cambios}`, `; also, {cambios}`, `; a més, {cambios}`],

    // ---- estilos
    [`Clásico`, `Classic`, `Clàssic`],
    [`Azul noche y terracota, el de siempre`, `Midnight blue and terracotta, as it has always been`, `Blau nit i terracota, el de sempre`],
    [`Pasaporte`, `Passport`, `Passaport`],
    [`Burdeos y oro, esquinas rectas y letra de imprenta`, `Burgundy and gold, square corners and printed lettering`, `Burdeus i or, cantonades rectes i lletra d'impremta`],
    [`Carpeta`, `Folder`, `Carpeta`],
    [`Cartulina de archivo, sello rojo y letra de máquina de escribir`, `Filing card, red stamp and typewriter lettering`, `Cartolina d'arxiu, segell vermell i lletra de màquina d'escriure`],
    [`Nórdico`, `Nordic`, `Nòrdic`],
    [`Blanco y aire, verde agua suave y formas redondeadas`, `White and air, soft aqua green and rounded shapes`, `Blanc i aire, verd aigua suau i formes arrodonides`],
    [`Contraste`, `Contrast`, `Contrast`],
    [`Amarillo y negro, bordes gruesos y sombras duras`, `Yellow and black, thick borders and hard shadows`, `Groc i negre, vores gruixudes i ombres dures`],
    [`Bosque`, `Forest`, `Bosc`],
    [`Verde hondo y albaricoque, formas de hoja`, `Deep green and apricot, leaf-shaped corners`, `Verd fons i albercoc, formes de fulla`],
    [`Píxeles`, `Pixels`, `Píxels`],
    [`Videojuego de 8 bits: esquinas escalonadas, letra pixelada y colores retro (en claro, pantalla de Game Boy)`, `8-bit video game: stepped corners, pixel lettering and retro colours (in light mode, a Game Boy screen)`, `Videojoc de 8 bits: cantonades esglaonades, lletra pixelada i colors retro (en clar, pantalla de Game Boy)`],
    [`Neón`, `Neon`, `Neó`],
    [`Rótulos luminosos: contornos que brillan en rosa y turquesa sobre la noche`, `Glowing signs: outlines that shine pink and turquoise against the night`, `Rètols lluminosos: contorns que brillen en rosa i turquesa sobre la nit`],
    [`Chicle`, `Bubblegum`, `Xiclet`],
    [`Rosa chicle, menta, limón y celeste: todo redondo, gordito y de colorines`, `Bubblegum pink, mint, lemon and sky blue: all round, chubby and colourful`, `Rosa xiclet, menta, llimona i cel: tot rodó, rodonet i de colors`],
  ];

  function construir(lista) {
    const salida = { en: {}, ca: {} };
    for (const [es, en, ca] of lista) { salida.en[es] = en; salida.ca[es] = ca; }
    return salida;
  }
  window.DICC_DOM = construir(DOM);
  window.DICC_CODIGO = construir(CODIGO);
})();
